### ISSUE TITLE
Creating array of objects.

### ISSUE THREAD

**Issue by detsam** [jprante/elasticsearch-jdbc#111]
Is there any way to create array of objects inside document by sql query with the labeled columns?

Say, I have the mapping:

``` javascript
{
    "item" : {
        "properties" : {
            "id" : {"type" : "integer", "store" : "yes"},
            "title" : { "type" : "string", "store" : "yes", "index" : "analyzed" },
            "keywords" : {
                "properties" : {
                    "name" : { "type" : "string", "store" : "yes"},
                    "weight" : {"type" : "integer", "store" : "yes"},
                }
            }
        }
    }
}
```

For the document like this:

``` javascript
{
    "id" : "100312",
    "title" : "Amazing black box",
    "keywords" : [
        { 
            "name" : "black",
            "weight" : 10,
        },
        {
            "name" : "box",
            "weight" : 0,
        },
        {
            "name" : "amazing",
            "weight" : 0,
        }
    ]
}
```

I did tried create this documents by sql query like this, but it's does not work for me:

``` SQL
SELECT 
    'store' AS '_index', 
    'item' AS '_type',
    item.id AS '_id', 
    item.id AS 'item.id',
    item.title AS 'item.title', 
    keyword.keyword_name AS 'item.keywords.name',   
    item_keyword.keyword_weight AS 'item.keywords.weight',
FROM 
    item 
LEFT JOIN 
    item_keyword
ON 
    item.id = item_keyword.item_id
LEFT JOIN 
    keyword 
ON 
    item_keyword.keyword_id = keyword.keyword_id
```

After this in my index I got documents like this:

``` javascript
{
                ...

                "_source": {
                    "item": {
                        "id": 100312,
                        "title": "Amazing black box",
                        "keywords": {
                            "weight": [
                                0,
                                10,
                            ],
                            "name": [
                                "amazing",
                                "black",
                                "box"
                            ]
                     }
               }

               ...
}
```

**Comment by barakab** [comment]
So for:
SELECT 
    'relations' AS _index,
    so.id AS '_id',
    so.CreatedTime AS 'order.CreatedTime',
    so.totalPrice as 'order.totalPrice',
    i.name AS 'order.item[name]',
    i.barcode AS 'order.item[barcode]'
FROM
    smartorder so
        LEFT JOIN
    smartorder_scanneditem smsi ON so.id = smsi.SmartOrder_id
        LEFT JOIN
    scanneditem si ON smsi.items_id = si.id
        LEFT JOIN
    item i ON si.item_id = i.id

We're getting:
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [order.item]
        at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:416)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeObject(ObjectMapper.java:557)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeNonDynamicArray(ObjectMapper.java:688)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeArray(ObjectMapper.java:607)
        at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:492)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeObject(ObjectMapper.java:557)
        at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:490)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:542)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:491)
        at org.elasticsearch.index.shard.service.InternalIndexShard.prepareIndex(InternalIndexShard.java:413)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:435)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:150)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardR
eplicationOperationAction.java:512)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationO
perationAction.java:419)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.ElasticsearchIllegalArgumentException: unknown property [name]
        at org.elasticsearch.index.mapper.core.StringFieldMapper.parseCreateFieldForString(StringFieldMapper.java:331)
        at org.elasticsearch.index.mapper.core.StringFieldMapper.parseCreateField(StringFieldMapper.java:277)
        at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:406)
        ... 16 more
[2015-03-25 11:09:04,737][ERROR][river.jdbc.BulkNodeClient] bulk [1] failed with 1 failed items, failure message = failure in bulk execution:
[0]: index [relations], type [jdbc], id [6], message [MapperParsingException[failed to parse [order.item]]; nested: ElasticsearchIllegalArgumentException[u
nknown property [name]]; ]
[2015-03-25 11:09:04,738][INFO ][river.jdbc.SimpleRiverMouth] stopping bulk mode for index jdbc and refreshing...

Any hint here please?
