### ISSUE TITLE
error while connecting river with oracle version 10.2.0.4

### ISSUE THREAD

**Issue by vijaydodla** [jprante/elasticsearch-jdbc#200]
Hi jprante
i'm trying to connect river with Oracle and getting following error .
[ERROR][org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverSource] while opening read connection: jdbc:oracle:thin://10.80.00.00:1521/DBNAME No suitable driver found for jdbc:oracle:thin://10.80.00.00:1521/DBNAME
java.sql.SQLException: No suitable driver found for jdbc:oracle:thin://10.80.00.00:1521/DBNAME
    at java.sql.DriverManager.getConnection(DriverManager.java:604)
    at java.sql.DriverManager.getConnection(DriverManager.java:221)
    at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverSource.connectionForReading(SimpleRiverSource.java:141)
    at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverSource.execute(SimpleRiverSource.java:260)
    at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverSource.fetch(SimpleRiverSource.java:235)
    at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverFlow.move(SimpleRiverFlow.java:129)
    at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverFlow.run(SimpleRiverFlow.java:88)
    at java.lang.Thread.run(Thread.java:722)
[2014-03-10 21:49:38,039][ERROR][org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverFlow] java.lang.NullPointerException
java.io.IOException: java.lang.NullPointerException
    at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverSource.fetch(SimpleRiverSource.java:239)
    at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverFlow.move(SimpleRiverFlow.java:129)
    at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverFlow.run(SimpleRiverFlow.java:88)
    at java.lang.Thread.run(Thread.java:722)

---

Did following before i started ES
1. ojdbc14.jar is added to lib folder of elasticsearch installed folder
2. added ojdbc14.jar to CLASSPATH
3. added ojdbc14.jar to /plugins/river-jdbc
4. posted following data via sense to ES
POST /_river/my_jdbc_river/_meta
{
    "type" : "jdbc",
    "jdbc" : {
    "driver": "com.oracle.jdbc.Driver",
    "url" : "jdbc:oracle:thin://10.88.00.00:1521/DATABASE",
        "user" : "DB_User",
        "password" : "pwd",
        "sql" : "select \* from table1"
    }
}
1. Got the above error .

Any help is really appreciated .

**Comment by JeevaArumugam** [comment]
We are using the ojdbc6.jar for elasticsearch-1.4.2, we are getting the below error. Kindly help us.

data][4] updating refresh_interval from [1s] to [-1]
[2015-03-10 11:43:03,312][ERROR][river.jdbc.SimpleRiverSource] while opening rea
d connection: jdbc:oracle:thin:@pmstst.comfin.ge.com:1521:PMST11 No suitable dri
ver found for jdbc:oracle:thin:@pmstst.comfin.ge.com:1521:PMST11
java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@pmstst.com
fin.ge.com:1521:PMST11
        at java.sql.DriverManager.getConnection(DriverManager.java:596)
        at java.sql.DriverManager.getConnection(DriverManager.java:187)
        at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverSource.g
etConnectionForReading(SimpleRiverSource.java:220)
        at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverSource.e
xecute(SimpleRiverSource.java:388)
        at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverSource.f
etch(SimpleRiverSource.java:332)
        at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverFlow.fet
ch(SimpleRiverFlow.java:220)
        at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverFlow.exe
cute(SimpleRiverFlow.java:149)
        at org.xbib.elasticsearch.plugin.jdbc.RiverPipeline.request(RiverPipelin
e.java:88)
        at org.xbib.elasticsearch.plugin.jdbc.RiverPipeline.call(RiverPipeline.j
ava:66)
        at org.xbib.elasticsearch.plugin.jdbc.RiverPipeline.call(RiverPipeline.j
ava:30)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:615)
        at java.lang.Thread.run(Thread.java:724)
