### ISSUE TITLE
Comma no longer works in schedule (cron syntax)

### ISSUE THREAD

**Issue by MichaelXt** [jprante/elasticsearch-jdbc#299]
Comma no longer works in schedule (cron syntax).

java.lang.IllegalArgumentException: invalid cron expression format: Unexpected end of expression
        at org.xbib.cron.CronExpression.buildExpression(CronExpression.java:287)
        at org.xbib.cron.CronExpression.<init>(CronExpression.java:101)
        at org.xbib.elasticsearch.plugin.feeder.AbstractFeeder.schedule(AbstractFeeder.java:177)
        at org.xbib.elasticsearch.plugin.river.jdbc.JDBCRiver.start(JDBCRiver.java:94)
        at org.elasticsearch.river.RiversService.createRiver(RiversService.java:148)

**Comment by loganbhardy** [comment]
Just confirming that I'm seeing the same issue with the latest elasticsearch-river-jdbc-1.4.0.8

"schedule": "0 1,16,31,46 * * * ? *",
throws the error
"schedule": "0 1/15 * * * ? *",
works fine
