### ISSUE TITLE
java.lang.OutOfMemoryError when using parameters in query

### ISSUE THREAD

**Issue by weph** [jprante/elasticsearch-jdbc#333]
I'm trying to import a table with about 50 million rows into elasticsearch with the jdbc river. At first I did a full import which worked like a charm:

```
{
    "sql": [{
        "statement": "select * from mytable"
    }]
}
```

As I need the ability to do incremental imports I started to experiment with the parameter feature and ran into an out of memory exception. The query below returns about 2.2 million rows and results in the exception. When I change the parameter to 2014-09-01 (360.000 rows) it works fine. I changed the fetchsize but this seemed to have no effect.

I tested on ES 1.3.2 with 1.3.0.4 and ES 1.2.4 with 1.2.2.0. Database is a MySQL 5.5.35, mysql-java-connector is 5.1.28.

```
{
    "sql": [{
        "statement": "select * from mytable where datefield > ?",
        "parameter": ["2014-08-01"]
    }]
}
```

```
java.lang.OutOfMemoryError: Java heap space
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:188)
    at org.xbib.pipeline.simple.SimplePipelineExecutor.waitFor(SimplePipelineExecutor.java:118)
    at org.xbib.elasticsearch.plugin.feeder.AbstractFeeder.run(AbstractFeeder.java:241)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.OutOfMemoryError: Java heap space
    at com.mysql.jdbc.Buffer.getBytes(Buffer.java:207)
    at com.mysql.jdbc.Buffer.readLenByteArray(Buffer.java:339)
    at com.mysql.jdbc.MysqlIO.nextRow(MysqlIO.java:2082)
    at com.mysql.jdbc.MysqlIO.readSingleRowSet(MysqlIO.java:3554)
    at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:491)
    at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:3245)
    at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:2413)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2836)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2825)
    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2156)
    at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2313)
    at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverSource.executeQuery(SimpleRiverSource.java:572)
    at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverSource.executeWithParameter(SimpleRiverSource.java:355)
    at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverSource.fetch(SimpleRiverSource.java:284)
    at org.xbib.elasticsearch.plugin.feeder.jdbc.JDBCFeeder.fetch(JDBCFeeder.java:335)
    at org.xbib.elasticsearch.plugin.feeder.jdbc.JDBCFeeder.executeTask(JDBCFeeder.java:179)
    at org.xbib.elasticsearch.plugin.feeder.AbstractFeeder.newRequest(AbstractFeeder.java:362)
    at org.xbib.elasticsearch.plugin.feeder.AbstractFeeder.newRequest(AbstractFeeder.java:53)
    at org.xbib.pipeline.AbstractPipeline.call(AbstractPipeline.java:87)
    at org.xbib.pipeline.AbstractPipeline.call(AbstractPipeline.java:14)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    ... 1 more
```

**Comment by youchenlee** [comment]
Sorry for reply a closed issue. Hope this help some people.

I ran into this issue. Finally found that the only solution to me is to optimize the sql statement, (which was too simple to be thought about.)
Add some proper db index to make sure the sql statement can be finish as soon as possible.

`select * from mytable` was fast, the major overhead is data transferring, and since we are doing a streaming import, data transferring is not a big deal. Through `select * from mytable where datefield > ?` should take a long time & lots of memory when you got millions of data without proper indexes.
