### ISSUE TITLE
cannot load from oracle

### ISSUE THREAD

**Issue by sdba2** [jprante/elasticsearch-jdbc#336]
i followed some links and didn't succeed to load from oracle.
here is what i did :
1. install the plugin under : plugins/river-jdbc
2. copy ojdbc6.jar into 2 places : the 1st is under plugins/river-jdbc and 2nd under : elasticsearch/lib
    (ls /use/share/elasticsearc/plugins/river-jdbc returns 4 files
         elasticsearch-river-jdbc-1.3.0.4.jar
         ojdbc6.jar
         log4j2.xml
         log4j.properties
3. try to load using :
   curl -XPUT 'localhost:9200/_river/my_oracle_driver/_meta -d '{
   "type" : "jdbc",
   "jdbc" : {
   "url" : "jdbc.oracle.thin:@//myhost1:1521/sid1",
   "user" : "user1",
   "password" : "p",
   "sql" : "select \* from a""
   }
   }'

the output is :
{"_index":"_river","_type":"my_oracle_driver","_id":"_meta","_version":1,"created":true}
1. what i end up with is 2 indexes
   _river (with 2 docs)
   jdbc (with 0 docs)  

what am i missing?
please advise

**Comment by otchi** [comment]
i have a same problem :+1: 
log4j:WARN No appenders could be found for logger (JDBCFeeder).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.xbib.elasticsearch.plugin.jdbc.feeder.Runner.main(Runner.java:45)
Caused by: java.lang.NullPointerException
        at org.xbib.elasticsearch.plugin.jdbc.feeder.JDBCFeeder.start(JDBCFeeder.java:169)
        at org.xbib.elasticsearch.plugin.jdbc.feeder.JDBCFeeder.exec(JDBCFeeder.java:110)
        ... 5 more
java.lang.NullPointerException
        at org.xbib.elasticsearch.plugin.jdbc.feeder.JDBCFeeder.shutdown(JDBCFeeder.java:239)
        at org.xbib.elasticsearch.plugin.jdbc.feeder.JDBCFeeder$1.run(JDBCFeeder.java:219)

***************************************************************************************************************
my feeder.bat is in %ES_HOME% 

@echo off

SETLOCAL

if NOT DEFINED ES_HOME goto err

set DIR=%~dp0

set FEEDER_CLASSPATH=%DIR%lib\*;%DIR%plugins\jdbc\*
 ECHO .............................
 ECHO %FEEDER_CLASSPATH%
    

echo {^
    "elasticsearch" : {^
         "cluster" : "elasticsearch",^
         "host" : "localhost",^
         "port" : 9300,^
         "type" : "jdbc",^
         "schedule" : "0 0 * * * *"^
    },^
    "jdbc" : {^
        "url": "jdbc:mysql://localhost:3306/test",^
        "user" : "root",^
        "password" : "KatiaAmine9294",^
        "sql":"select * from amine",^
        "treat_binary_as_string" : true,^
        "index" : "metawiki",^
      }^
}^ | "%JAVA_HOME%\bin\java" -cp "%FEEDER_CLASSPATH%" "org.xbib.elasticsearch.plugin.jdbc.feeder.Runner" "org.xbib.elasticsearch.plugin.jdbc.feeder.JDBCFeeder" 
goto finally

:err
echo JAVA_HOME and ES_HOME environment variable must be set!
pause


:finally

ENDLOCAL
*******************************************************************************************************
I installed before  jdbc plugin : 
plugin --install jdbc --url http://xbib.org/xbib/elasticsearch/plugin/elasticsearch-river-jdbc/1.4.4.0/elasticsearch-river-jdbc-1.4.4.0-plugin.zip

and i put JDBC driver in the same directory 

******************************************************************************************************
Thank you in advance for your help .
:+1:
