### ISSUE TITLE
Unable to setup Cron for incremental data, NPE while using last.sql.end / river.state.last_active_begin

### ISSUE THREAD

**Issue by siddhanth** [jprante/elasticsearch-jdbc#418]
Currently I am on version 1.3.4.6. I want to incrementally pull the data into ES. I tried using river.state.last_active_begin as a sql parameter but instead of taking the last time the river ran it was taking the current time.  The I tried using  $sql.last.end to synchronise the cron for the river. But its throwing a null pointer exception. I even tried $river.state.last_active_end but even that was giving me a NPE.

River config.
curl -XPUT 'a.b.c.d:9200/_river/tracking_river/_meta' -d '{
    "strategy": "simple",
    "schedule" : "0 _/1 \* \* \* ?",
    "type" : "jdbc",
    "jdbc" : {
        "url" : "jdbc:mysql://localhost:3306/abcd",
        "user" : "root",
        "password" : "abcd",
        "sql" : [
            {
                "statement": "select a._ , a.cc*1000 timestamp  from tracking a where a.gid=3 and inserted_at  > ?",
                "parameter": [ "$last.sql.end" ]
            }
        ],
        "index" : "tracking",
        "type" : "tracking"  
    }
}'

Here is the log for the NPE.
java.io.IOException: java.lang.NullPointerException
        at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverSource.fetch(SimpleRiverSource.java:341)
        at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverFlow.fetch(SimpleRiverFlow.java:220)
        at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverFlow.execute(SimpleRiverFlow.java:149)
        at org.xbib.elasticsearch.plugin.jdbc.RiverPipeline.request(RiverPipeline.java:88)
        at org.xbib.elasticsearch.plugin.jdbc.RiverPipeline.call(RiverPipeline.java:66)
        at org.xbib.elasticsearch.plugin.jdbc.RiverPipeline.call(RiverPipeline.java:30)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by siddhanth** [comment]
It will be really great if we can fix this issue as soon as possible.

**Comment by jprante** [comment]
Did you delete the _river index and recreate river instances when using the fix versions?
