### ISSUE TITLE
Fail-over / Backup database ?

### ISSUE THREAD

**Issue by redi-tjandr** [jprante/elasticsearch-jdbc#526]
Before I create a new Strategy, I'm wondering if there's an already created solution that allows you to specify backup / failover databases that are replica's of the original and pull from those if the primary is down?

**Comment by jprante** [comment]
There are a number of failover mechanisms on JDBC driver level, depending on database.

**Comment by redi-tjandr** [comment]
Thanks for the quick response.  On a related note, another question.  If we have a cluster of elasticsearch instances and are using the feeder, how do we specify multiple IP addresses for the hosts in the cluster?  So for example:

"elasticsearch":{
        "cluster":"cluster-name",
        "host":"10.x.x.y,10.x.x.z",
        "port":9300
    }

Does a comma separated list work or something else?  Also I would only want to write to one of them, not both.

**Comment by redi-tjandr** [comment]
Looking at BaseTransportClient, it seems if you specify a host you can only specify one, and it will hit the "default" condition, which then only allows for a single address to be added.  Our use-case is if the IP address we specify is down, but the other host in the cluster is up, we would want to at least connect to the other node.  Is this supported and I'm not seeing it, or do we need a code enhancement to get this to work?

**Comment by jprante** [comment]
I have committed an improvement

https://github.com/jprante/elasticsearch-jdbc/commit/029bfbcb20ca944d210c55efdcaf95f8ab3dbe05

You can specify a list of host names to connect to, like this

	"elasticsearch":{
		"cluster":"cluster-name",
		"host": ["10.x.y.z:9300", "10.x.y.z:9301"],
		"autodiscover" :true
	}

The host name specification is `host:port` where `host` follows the logical host ES description at http://www.elastic.co/guide/en/elasticsearch/reference/1.x/modules-network.html

With `autodiscover` set to `true`, JDBC feeder will try to connect to all cluster nodes (default is `false`).

**Comment by redi-tjandr** [comment]
Awesome, looks like it would work, when is the next release expected?  Just trying to see if I need to build locally or wait on official release

**Comment by jprante** [comment]
I have pushed out versions 1.5.0.1 and 1.4.4.1 with the improvement.

**Comment by redi-madhava** [comment]
Awesome! Thanks Jorg!

**Comment by redi-tjandr** [comment]
Thanks! Do you happen to know if either of those is compatible with Elastic Search 1.4.0 or know where I can find compatibility matrix?

**Comment by jprante** [comment]
You can see at at the versioning scheme, JDBC Plugin 1.4.x.y  is compatible with ES 1.4.x, JDBC plugin 1.5.x.y with ES 1.5.x

**Comment by redi-tjandr** [comment]
I think there's a bug in the new code.  If I put in more than one host, when it prints the settings in JDBCFeeder (line 143 in the 1.4.4.1 code), it says something like"

settings = {elasticsearch.host.0=.... elasticsearch.host.1=....}

And since it's mapped to elasticsearch.host.0 instead of elasticsearch.host, this line of code fails in JDBCFeeder line 257:

                        .put("host", settings.get("elasticsearch.host", "localhost"))

So it always gets converted to 'localhost' if there is ever more than one item in the list.

**Comment by jprante** [comment]
OK, I missed that, will be fixed tomorrow.

**Comment by jprante** [comment]
Next try, now the versions are 1.4.4.2 and 1.5.0.2

**Comment by redi-tjandr** [comment]
Thanks for quick turnaround, still a bug though.  Now it's giving an error like this:

JDBCFeeder:135 - [Ljava.lang.String;@254ce181: invalid IPv6 address

In other words, I think it's trying to parse an array object as a String in BaseTransportClient line 125 for the host.

**Comment by jprante** [comment]
Next try, now I added a test to confirm the feeder settings work: 1.4.4.3 and 1.5.0.3

**Comment by redi-tjandr** [comment]
Thanks, that error is definitely fixed, but now I'm getting a different bug:

Everything works with 1.4.0 version of elasticsearch jar (client) and river version 1.4.0.8.jar with elasticsearch server version of 1.4.2.

For 1.4.4.3 version of jdbc river and any of the following: 1.4.0 or 1.4.2 or 1.4.4 version of elasticsearch client with same server version of 1.4.2:

When I do autodiscover:true I get this error:
2015-04-17 17:09:31,600  WARN netty:135 - [feeder] Message not fully read (response) for [3] handler org.elasticsearch.action.TransportActionNodeProxy$1@62ef6486, error [false], resetting
And it just dies after that.

If I remove the autodiscover:true part, I get the following:
2015-04-17 17:12:30,041  WARN netty:135 - [feeder] Message not fully read (response) for [13] handler org.elasticsearch.action.TransportActionNodeProxy$1@4555e4a3, error [false], resetting
2015-04-17 17:12:30,042  WARN SimpleRiverFlow:260 - no river mouth
2015-04-17 17:12:30,042 ERROR RiverPipeline:90 - Failed to deserialize response of type [org.xbib.elasticsearch.action.plugin.jdbc.state.get.GetRiverStateResponse]
org.elasticsearch.transport.TransportSerializationException: Failed to deserialize response of type [org.xbib.elasticsearch.action.plugin.jdbc.state.get.GetRiverStateResponse]
        at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:152)
        at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:127)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Can't read unknown type [69]
        at org.elasticsearch.common.io.stream.StreamInput.readGenericValue(StreamInput.java:434)
        at org.elasticsearch.common.io.stream.StreamInput.readMap(StreamInput.java:358)
        at org.xbib.elasticsearch.plugin.jdbc.state.RiverState.readFrom(RiverState.java:302)
        at org.xbib.elasticsearch.action.plugin.jdbc.state.get.GetRiverStateResponse.readFrom(GetRiverStateResponse.java:73)
        at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:150)
        ... 23 more
2015-04-17 17:12:30,045 DEBUG RiverPipeline:69 - releasing river context
2015-04-17 17:12:30,046 DEBUG RiverThread:140 - river flow org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverFlow@26a5d04b thread is finished

**Comment by redi-tjandr** [comment]
You mentioned 1.4.x elasticsearch river works with 1.4 elastic search, but I'm wondering if my 1.4.2 server isn't going to be able to talk to this 1.4.4 version of the jdbc river plugin?  Does that stack trace ring any bells to you?  I very much appreciate all the help by the way!

**Comment by jprante** [comment]
`Can't read unknown type` is an error caused by ES stream serialization, do you run different JDBC plugins versions in the cluster?

**Comment by redi-tjandr** [comment]
Nope, I have version jdk1.7.0_02 on both the cluster servers as well as the server I'm using the feeder for.  Also, the fact that it works when switching from feeder version 1.4.0.8 of the river plugin but not the 1.4.4.3 version makes me think java version isn't necessarily the issue.

**Comment by redi-tjandr** [comment]
Ah, found my problem (user error).  It was I needed to update the server version of the river jdbc plugin as well as the version on my feeder box to be in synch.  It appears to work now!

**Comment by redi-madhava** [comment]
Jorg,what is the reason that river jdbc plugin has to be installed as a plugin in elasticsearch even when we run it in feeder mode? Does the feeder talk to river jdbc plugin code running inside elasticsearch?

**Comment by jprante** [comment]
The plugin installation peculiarity will be removed soon. It is there for historical reasons only. It only adds some river state to the cluster state, and is more a burden than a relief. In a later version, the feeder will keep its own state, independent of ES.

**Comment by redi-tjandr** [comment]
So if we want to use $river.state.last_active_begin in our query, what I'm noticing is pre 1.4.4 if it was null it would basically start from current startup time.  After 1.4.4 (https://github.com/jprante/elasticsearch-jdbc/pull/489) it pulls from beginning of time after starting up and every subsequent startup.  So just to confirm, the current way of running as a feeder doesn't persist state to actually use last_active_begin between startups of the application, right?

**Comment by jprante** [comment]
`$river.state.last_active_begin` is only valid for a river instance while running. I can not find a method how to persist state. I was told that keeping the state between mode restarts is a bug. So I will remove all river state related code in a later version, and save feeder arguments in a simple file.

**Comment by redi-tjandr** [comment]
Thanks Jorg, quick question about specifying multiple host IP's.  If I were to specify 2 IP's in my cluster, does ESFeeder actually write data to both, or does it only write to one and elasticsearch disperses the data to the other nodes?  I'm assuming it only writes to one, but just need to confirm that's the implementation.

**Comment by jprante** [comment]
First, it tries to connect to the give IPs. Second, it `autodiscover` is set to `true`, JDBC plugin downloads the list of all nodes in the cluster and tries to connect to those nodes (so you don't have to enumerate all nodes explicitly in case you want to connect to all nodes). Then, it works like all other TransportClient connections. Every action call (here the bulk index request) is proxied by this method to a random connected node https://github.com/elastic/elasticsearch/blob/master/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java#L199
After the node has received the request, the bulk request is partitioned into smaller requests and forwarded to the nodes that hold the corresponding shards. So, the TransportClient random selection is only for distributing the "data transport and connection overhead" between the nodes, not the indexing workload, which depends on the shard locations.
