### ISSUE TITLE
River has not responded for 1 day and 7 hours

### ISSUE THREAD

**Issue by sawickil** [jprante/elasticsearch-jdbc#527]
Hey there! I've got a really strange issue with the jdbc-river v1.3.4. Maybe some of you have similar experience or can advice something. To be detailed - we use the column river strategy, but I believe it does not affect the main problem.

Generally, the river had been working correctly for 2 weeks and fetched over 40 millions records. Then something happened - the river started its execution and the last entries in the logs were:

`[2015-04-06 03:01:00,049][INFO ][<removed>.CryptoColumnRiverSource] fetch state={"name":"transactions_delta_river","type":"jdbc","started":"2015-03-18T23:33:00.016Z","last_active_begin":"2015-04-06T01:01:00.007Z","last_active_end":"2015-04-06T01:00:11.818Z","map":{"last_run_time":"2015-04-06T01:00:00.050Z","aborted":false,"suspended":false,"counter":25897}}`

`[2015-04-06 03:01:00,214][DEBUG][<removed>.CryptoColumnRiverSource] lastRunTimestamp=2015-04-06 02:56:00.05`

`[2015-04-06 03:01:00,214][DEBUG][<removed>.CryptoColumnRiverSource] opinfo=index ("TRANS_UPDATE_DATE" >= ?) 1`

`[2015-04-06 03:01:00,214][DEBUG][<removed>.CryptoColumnRiverSource] sql: SELECT TRANS_ID as "_id",  ('transactions_' || TO_CHAR(TRANS_CREATE_DATE, 'YYYYMM')) AS "_index" <removed>), params [2015-04-06 02:56:00.05]`

`[2015-04-06 03:01:10,015][INFO ][river.jdbc.RiverMetrics  ] pipeline org.xbib.elasticsearch.plugin.jdbc.RiverPipeline@449a05b5 is running: river jdbc/transactions_delta_river metrics: 40385351 rows, 26.498919388248563 mean, (28.24872631158366 6.448405864180694 2.1976788366558604), ingest metrics: elapsed 10 seconds, 0.0 bytes bytes, 0.0 bytes avg, 0 MB/s`

...and then nothing happened. I mean, there were only the metrics logs like the one above (with the same rows count) and internal elastic server logs. 

After 1 day and 7 hours and when the tons of metrics logs were produced the last metrics log said:
`[2015-04-07 10:39:10,014][INFO ][river.jdbc.RiverMetrics  ] pipeline org.xbib.elasticsearch.plugin.jdbc.RiverPipeline@449a05b5 is running: river jdbc/transactions_delta_river metrics: 40385351 rows, 24.65652096132817 mean, (28.24872631158366 6.448405864180694 2.1976788366558604), ingest metrics: elapsed 1 day 7 hours 38 minutes 10 seconds, 0.0 bytes bytes, 0.0 bytes avg, 0 MB/s`

Hopefully, that day we had to update river, so we removed it and created a new one, which stopped the previous locked instance. Here are some logs which appeared while we were removing the old one and creating the new version of the river:
`[2015-04-07 10:40:05,469][DEBUG][river.jdbc.JDBCRiver     ] shutting down river thread scheduler
[2015-04-07 10:40:05,471][DEBUG][river.jdbc.JDBCRiver     ] interrupting river thread
[2015-04-07 10:40:05,471][INFO ][river.jdbc.JDBCRiver     ] river closed [jdbc/transactions_delta_river]
[2015-04-07 10:40:05,480][DEBUG][river.jdbc.RiverThread   ] shutting down metrics thread scheduler
[2015-04-07 10:40:05,480][DEBUG][river.jdbc.RiverThread   ] shutting down suspension thread scheduler
[2015-04-07 10:40:05,480][WARN ][river.jdbc.RiverThread   ] interrupted
[2015-04-07 10:40:05,480][ERROR][river.jdbc.RiverThread   ] interrupted while shutdown
java.io.IOException: interrupted while shutdown
	at org.xbib.elasticsearch.plugin.jdbc.pipeline.executor.SimplePipelineExecutor.shutdown(SimplePipelineExecutor.java:145)
	at org.xbib.elasticsearch.plugin.jdbc.RiverThread.afterPipelineExecutions(RiverThread.java:140)
	at org.xbib.elasticsearch.plugin.jdbc.RiverThread.run(RiverThread.java:130)
	at java.lang.Thread.run(Thread.java:745)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2015-04-07 10:40:05,481][DEBUG][river.jdbc.RiverThread   ] river flow com.payu.elasticsearch.CryptoColumnRiverFlow@66ac11d0 thread is finished
[2015-04-07 10:40:05,502][DEBUG][river                    ] [TRANSACTIONAL_ELASTIC_2] failed to (double) delete river [transactions_delta_river] content
org.elasticsearch.transport.RemoteTransportException: [TRANSACTIONAL_ELASTIC_3][inet[/10.81.20.77:9300]][indices/mapping/delete]
Caused by: org.elasticsearch.indices.TypeMissingException: [_all] type[[transactions_delta_river]] missing: No index has the type.
	at org.elasticsearch.action.admin.indices.mapping.delete.TransportDeleteMappingAction$1.onResponse(TransportDeleteMappingAction.java:135)
	at org.elasticsearch.action.admin.indices.mapping.delete.TransportDeleteMappingAction$1.onResponse(TransportDeleteMappingAction.java:114)
....
`

For me, this entire thing looks like some kind of lock happend in the river code, but currently I don't have any idea why and how to prove this.  Any thoughts?

**Comment by jprante** [comment]
From the logs there is nothing of interest which would allow to diagnose such a hangup. It looks pretty normal, the metrics thread allowed to discover the stuck river, and the restart is logged as expected.

Maybe the JDBC database driver locked up, waiting on a dead network socket, for example.

In this case, a thread dump might help, see `jstack` http://docs.oracle.com/javase/7/docs/technotes/tools/share/jstack.html In the dump, the JDBC plugin threads are revealed beside ES threads, and would allow to diagnose where they hang.

**Comment by sawickil** [comment]
Thanks Jorg. I also think the thread dump looks the only reasonable way in this case
