### ISSUE TITLE
org.elasticsearch.common.settings.NoClassSettingsException: Failed to load class with value [jdbc]

### ISSUE THREAD

**Issue by qianglu1989** [jprante/elasticsearch-jdbc#528]
org.elasticsearch.common.settings.NoClassSettingsException: Failed to load class with value [jdbc]
        at org.elasticsearch.river.RiverModule.loadTypeModule(RiverModule.java:87)
        at org.elasticsearch.river.RiverModule.spawnModules(RiverModule.java:58)
        at org.elasticsearch.common.inject.ModulesBuilder.add(ModulesBuilder.java:44)
        at org.elasticsearch.river.RiversService.createRiver(RiversService.java:137)
        at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:273)
        at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:267)
        at org.elasticsearch.action.support.TransportAction$ThreadedActionListener$1.run(TransportAction.java:113)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: jdbc
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.elasticsearch.river.RiverModule.loadTypeModule(RiverModule.java:73)
        ... 9 more

**Comment by jprante** [comment]
You did not install the JDBC plugin.

**Comment by qianglu1989** [comment]
Thank you very much, I don't have to restart es

**Comment by adnangul** [comment]
Getting same, I've installed the jdbc plugin and verified using 

C:\Java\elasticsearch-1.6.0\bin>plugin -l
Installed plugins:
    - HQ
    - jdbc
    - license
    - marvel
    - watcher
