### ISSUE TITLE
Connection properties for JDBC driver,question

### ISSUE THREAD

**Issue by qianglu1989** [jprante/elasticsearch-jdbc#530]
I configured the index,start successful
It seems that the info is there
{"took":3,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}

my index 
curl -XPUT 'localhost:9200/_river/my_oracle_river/_meta' -d '{
    "type" : "jdbc",
    "jdbc" : {
        "url" : "jdbc:oracle:thin:@//10.16.0.156:1521/ebbc",
        "user" : "ebbc",
        "password" : "ebbc",
        "sql" : "select id as _id,user_id,trans_name  from  t_gnr_operate_list",
        "index" : "ebbc-operate",
        "type" : "operate",
        "connection_properties" : {
            "oracle.jdbc.TcpNoDelay" : false,
            "useFetchSizeWithLongColumn" : false,
            "oracle.net.CONNECT_TIMEOUT" : 10000,
            "oracle.jdbc.ReadTimeout" : 50000
        }
    }
}'

**Comment by qianglu1989** [comment]
I waited for a long time, but there is no data synchronization to I ES

**Comment by jprante** [comment]
Check the log files for error messages.

**Comment by qianglu1989** [comment]
the logs 
[2015-04-14 21:37:14,885][INFO ][cluster.routing.allocation.decider] [ebbc-node1] low disk watermark [15%] exceeded on [gw-B923HTjq9pHqpU_iH3A][ebbc-node2] free: 1.1gb[11.6%], replicas will not be assigned to this node

**Comment by jprante** [comment]
This is not a JDBC plugin message, and it is not an error message.

**Comment by qianglu1989** [comment]
where the logs file

**Comment by jprante** [comment]
The Elasticsearch log files are in the logs folder, ES_HOME/logs

**Comment by qianglu1989** [comment]
This I know, but found no error pugin log,Is it only when creating an index have a log, I'll take a closer look

**Comment by qianglu1989** [comment]
The error log


[2015-04-15 09:14:30,562][ERROR][river.jdbc.RiverPipeline ] java.sql.SQLSyntaxErrorException: ORA-00911: invalid character

java.io.IOException: java.sql.SQLSyntaxErrorException: ORA-00911: invalid character

        at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverSource.fetch(SimpleRiverSource.java:353)
        at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverFlow.fetch(SimpleRiverFlow.java:226)
        at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverFlow.execute(SimpleRiverFlow.java:152)
        at org.xbib.elasticsearch.plugin.jdbc.RiverPipeline.request(RiverPipeline.java:88)
        at org.xbib.elasticsearch.plugin.jdbc.RiverPipeline.call(RiverPipeline.java:66)
        at org.xbib.elasticsearch.plugin.jdbc.RiverPipeline.call(RiverPipeline.java:30)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00911: invalid character

        at oracle.jdbc.driver.SQLStateMapping.newSQLException(SQLStateMapping.java:91)
        at oracle.jdbc.driver.DatabaseError.newSQLException(DatabaseError.java:112)
        at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:173)
        at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:455)
        at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:413)
        at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:1030)
        at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:183)
        at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:774)
        at oracle.jdbc.driver.T4CStatement.executeMaybeDescribe(T4CStatement.java:849)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1178)
        at oracle.jdbc.driver.OracleStatement.executeQuery(OracleStatement.java:1377)
        at oracle.jdbc.driver.OracleStatementWrapper.executeQuery(OracleStatementWrapper.java:386)
        at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverSource.executeQuery(SimpleRiverSource.java:685)
        at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverSource.execute(SimpleRiverSource.java:403)
        at org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverSource.fetch(SimpleRiverSource.java:332)
        ... 9 more

**Comment by qianglu1989** [comment]
thanks you very much,i think i have found error
