### ISSUE TITLE
_state is not removed after deleting river

### ISSUE THREAD

**Issue by loganbhardy** [jprante/elasticsearch-jdbc#538]
Elasticsearch 1.5.1 & elasticsearch-river-jdbc-1.5.0.0

I run a one-time river then delete it but the _state persists. Here are all the river logs I captured from each node in my cluster. 

.....
[2015-04-17 22:55:02,341][DEBUG][river.jdbc.BulkNodeClient] after bulk [87] [succeeded=129554] [failed=0] [534ms] 0 concurrent requests
[2015-04-17 22:55:06,868][DEBUG][river.jdbc.BulkNodeClient] before bulk [89] [actions=1839] [bytes=10489555] [concurrent requests=2]
[2015-04-17 22:55:07,050][DEBUG][river.jdbc.BulkNodeClient] before bulk [90] [actions=54] [bytes=311707] [concurrent requests=2]
[2015-04-17 22:55:07,094][DEBUG][river.jdbc.BulkNodeClient] after bulk [90] [succeeded=129608] [failed=0] [43ms] 1 concurrent requests
[2015-04-17 22:55:08,394][DEBUG][river.jdbc.BulkNodeClient] after bulk [89] [succeeded=131447] [failed=0] [1525ms] 0 concurrent requests
[2015-04-17 22:55:08,529][DEBUG][river.jdbc.SimpleRiverSource] merged 132513 rows
[2015-04-17 22:55:08,549][DEBUG][river.jdbc.SimpleRiverFlow] after fetch: state posted = {"name":"sales-river-one-time","type":"jdbc","started":"2015-04-17T22:47:58.941Z","last_active_begin":"2015-04-17T22:47:59.004Z","current_active_begin":"2015-04-17T22:47:59.004Z","last_active_end":"2015-04-17T22:55:08.529Z","map":{"lastStartDate":1429310879024,"lastExecutionEndDate":1429311308529,"counter":1,"lastExecutionStartDate":1429310879060}}
[2015-04-17 22:55:08,549][DEBUG][river.jdbc.BulkNodeClient] flushing bulk processor
[2015-04-17 22:55:08,551][DEBUG][river.jdbc.BulkNodeClient] before bulk [91] [actions=589] [bytes=3391746] [concurrent requests=1]
[2015-04-17 22:55:08,710][DEBUG][river.jdbc.BulkNodeClient] after bulk [91] [succeeded=132036] [failed=0] [159ms] 0 concurrent requests
[2015-04-17 22:55:11,947][DEBUG][river.jdbc.BulkNodeClient] closing bulk processor...
[2015-04-17 22:55:11,947][DEBUG][river.jdbc.BulkNodeClient] shutting down...
[2015-04-17 22:55:11,947][DEBUG][river.jdbc.BulkNodeClient] shutting down completed
[2015-04-17 22:55:11,974][DEBUG][river.jdbc.SimpleRiverSource] read connection closed
[2015-04-17 22:55:11,974][DEBUG][river.jdbc.SimpleRiverSource] write connection closed
[2015-04-17 22:55:11,980][INFO ][river.jdbc.RiverMetrics  ] pipeline org.xbib.elasticsearch.plugin.jdbc.RiverPipeline@4bc2fdc5 complete: river jdbc/sales-river-one-time metrics: 132513 rows, 305.99794623778723 mean, (372.3608061953475 257.6914963743041 121.40425887826822), ingest metrics: elapsed 7 minutes 12 seconds, 710.42 MB bytes, 5.49 KB avg, 1.641 MB/s
[2015-04-17 22:55:11,980][DEBUG][river.jdbc.RiverPipeline ] releasing river context
[2015-04-17 22:55:11,981][DEBUG][river.jdbc.BulkNodeClient] flushing bulk processor
[2015-04-17 22:55:11,981][DEBUG][river.jdbc.BulkNodeClient] no current ingests
[2015-04-17 22:55:11,981][DEBUG][river.jdbc.SimpleRiverSource] read connection closed
[2015-04-17 22:55:11,981][DEBUG][river.jdbc.SimpleRiverSource] write connection closed
[2015-04-17 22:55:11,982][DEBUG][river.jdbc.RiverThread   ] river flow org.xbib.elasticsearch.river.jdbc.strategy.simple.SimpleRiverFlow@131f0575 thread is finished
[2015-04-17 22:58:54,897][DEBUG][river.cluster            ] [Madelyne Pryor] processing [received_state]: execute
[2015-04-17 22:58:54,897][DEBUG][river.cluster            ] [Madelyne Pryor] cluster state updated, version [2], source [received_state]
[2015-04-17 22:58:54,898][DEBUG][river                    ] [Madelyne Pryor] closing river [jdbc][sales-river-one-time]
[2015-04-17 22:58:54,898][DEBUG][river.jdbc.JDBCRiver     ] shutting down river thread scheduler
[2015-04-17 22:58:54,898][DEBUG][river.jdbc.JDBCRiver     ] interrupting river thread
[2015-04-17 22:58:54,898][DEBUG][river.jdbc.JDBCRiver     ] shutting down river flow
[2015-04-17 22:58:54,898][INFO ][river.jdbc.JDBCRiver     ] river closed [jdbc/sales-river-one-time]

.....
[2015-04-17 22:44:12,039][DEBUG][river.cluster            ] [Kilmer] processing [reroute_rivers_node_changed]: execute
[2015-04-17 22:44:12,039][DEBUG][river.cluster            ] [Kilmer] processing [reroute_rivers_node_changed]: no change in cluster_state
[2015-04-17 22:44:12,057][DEBUG][river.cluster            ] [Kilmer] processing [reroute_rivers_node_changed]: execute
[2015-04-17 22:44:12,057][DEBUG][river.cluster            ] [Kilmer] processing [reroute_rivers_node_changed]: no change in cluster_state
[2015-04-17 22:44:26,905][DEBUG][river.cluster            ] [Kilmer] processing [reroute_rivers_node_changed]: execute
[2015-04-17 22:44:26,905][DEBUG][river.cluster            ] [Kilmer] processing [reroute_rivers_node_changed]: no change in cluster_state
[2015-04-17 22:47:57,825][DEBUG][river.cluster            ] [Kilmer] processing [reroute_rivers_node_changed]: execute
[2015-04-17 22:47:57,842][DEBUG][river.routing            ] [Kilmer] no river _meta document found retrying in 1000 ms
[2015-04-17 22:47:57,842][DEBUG][river.cluster            ] [Kilmer] processing [reroute_rivers_node_changed]: no change in cluster_state
[2015-04-17 22:47:58,843][DEBUG][river.cluster            ] [Kilmer] processing [reroute_rivers_node_changed]: execute
[2015-04-17 22:47:58,851][DEBUG][river.routing            ] [Kilmer] _river/sales-river-one-time/_meta document found.
[2015-04-17 22:47:58,854][DEBUG][river.routing            ] [Kilmer] going to allocate river [sales-river-one-time] on node [Madelyne Pryor][233VLIPbRem_zHJEMLqz9A][ip-192-168-211-199][inet[/192.168.211.199:9300]]{data=false, master=false}
[2015-04-17 22:47:58,854][DEBUG][river.cluster            ] [Kilmer] cluster state updated, version [1], source [reroute_rivers_node_changed]
[2015-04-17 22:47:58,856][DEBUG][river.cluster            ] [Kilmer] processing [reroute_rivers_node_changed]: done applying updated cluster_state
[2015-04-17 22:47:58,956][DEBUG][river.jdbc.RiverStateService] put: first river state [jdbc/sales-river-one-time]
[2015-04-17 22:47:58,979][DEBUG][river.cluster            ] [Kilmer] processing [reroute_rivers_node_changed]: execute
[2015-04-17 22:47:58,979][DEBUG][river.cluster            ] [Kilmer] processing [reroute_rivers_node_changed]: no change in cluster_state
[2015-04-17 22:47:59,002][DEBUG][river.cluster            ] [Kilmer] processing [reroute_rivers_node_changed]: execute
[2015-04-17 22:47:59,002][DEBUG][river.cluster            ] [Kilmer] processing [reroute_rivers_node_changed]: no change in cluster_state
[2015-04-17 22:47:59,014][DEBUG][river.jdbc.RiverStateService] post: update river state = {"name":"sales-river-one-time","type":"jdbc","started":"2015-04-17T22:47:58.941Z","last_active_begin":"1970-01-01T00:00:00.000Z","current_active_begin":null,"last_active_end":null,"map":{"aborted":false,"suspended":false,"counter":1}}
[2015-04-17 22:47:59,030][DEBUG][river.cluster            ] [Kilmer] processing [reroute_rivers_node_changed]: execute
[2015-04-17 22:47:59,030][DEBUG][river.cluster            ] [Kilmer] processing [reroute_rivers_node_changed]: no change in cluster_state
[2015-04-17 22:47:59,057][DEBUG][river.cluster            ] [Kilmer] processing [reroute_rivers_node_changed]: execute
[2015-04-17 22:47:59,057][DEBUG][river.cluster            ] [Kilmer] processing [reroute_rivers_node_changed]: no change in cluster_state
[2015-04-17 22:55:08,537][DEBUG][river.jdbc.RiverStateService] post: update river state = {"name":"sales-river-one-time","type":"jdbc","started":"2015-04-17T22:47:58.941Z","last_active_begin":"2015-04-17T22:47:59.004Z","current_active_begin":null,"last_active_end":"2015-04-17T22:55:08.529Z","map":{"lastStartDate":1429310879024,"counter":1,"aborted":false,"suspended":false,"lastExecutionEndDate":1429311308529,"lastExecutionStartDate":1429310879060}}
[2015-04-17 22:55:08,555][DEBUG][river.cluster            ] [Kilmer] processing [reroute_rivers_node_changed]: execute
[2015-04-17 22:55:08,555][DEBUG][river.cluster            ] [Kilmer] processing [reroute_rivers_node_changed]: no change in cluster_state
[2015-04-17 22:55:08,739][DEBUG][river.cluster            ] [Kilmer] processing [reroute_rivers_node_changed]: execute
[2015-04-17 22:55:08,739][DEBUG][river.cluster            ] [Kilmer] processing [reroute_rivers_node_changed]: no change in cluster_state
[2015-04-17 22:58:54,903][DEBUG][river.cluster            ] [Kilmer] processing [reroute_rivers_node_changed]: execute
[2015-04-17 22:58:54,904][DEBUG][river.cluster            ] [Kilmer] cluster state updated, version [2], source [reroute_rivers_node_changed]
[2015-04-17 22:58:54,904][DEBUG][river.cluster            ] [Kilmer] processing [reroute_rivers_node_changed]: done applying updated cluster_state

[2015-04-17 22:47:58,858][DEBUG][river.cluster            ] [Beautiful Dreamer] processing [received_state]: execute
[2015-04-17 22:47:58,858][DEBUG][river.cluster            ] [Beautiful Dreamer] cluster state updated, version [1], source [received_state]
[2015-04-17 22:47:58,858][DEBUG][river.cluster            ] [Beautiful Dreamer] processing [received_state]: done applying updated cluster_state
[2015-04-17 22:58:54,904][DEBUG][river.cluster            ] [Beautiful Dreamer] processing [received_state]: execute
[2015-04-17 22:58:54,904][DEBUG][river.cluster            ] [Beautiful Dreamer] cluster state updated, version [2], source [received_state]
[2015-04-17 22:58:54,904][DEBUG][river.cluster            ] [Beautiful Dreamer] processing [received_state]: done applying updated cluster_state

**Comment by jprante** [comment]
In the logs, there must be a line "river state deleted" after "river closed, see https://github.com/jprante/elasticsearch-jdbc/commit/b3a913cf06dba6fe91f43a16796bdfdf93bc82bc

Please update. I'm not sure why 1.5.0.0 does not contain state deletion.

**Comment by loganbhardy** [comment]
"river state deleted" is for sure not in the logs. 

I restarted the cluster and now I see "river state deleted" when I remove rivers and things appear to be working correctly but should I be concerned with the double delete message?


[2015-04-20 17:41:35,589][DEBUG][river.jdbc.JDBCRiver     ] shutting down river thread scheduler
[2015-04-20 17:41:35,589][DEBUG][river.jdbc.JDBCRiver     ] interrupting river thread
[2015-04-20 17:41:35,589][DEBUG][river.jdbc.JDBCRiver     ] shutting down river flow
[2015-04-20 17:41:35,589][INFO ][river.jdbc.JDBCRiver     ] river closed [jdbc/test5]
[2015-04-20 17:41:35,593][DEBUG][river.jdbc.RiverStateService] delete: river state [test5]
[2015-04-20 17:41:35,602][INFO ][river.jdbc.JDBCRiver     ] river state deleted [jdbc/test5]
[2015-04-20 17:41:35,602][DEBUG][river.cluster            ] [Ectokid] processing [reroute_rivers_node_changed]: done applying updated cluster_state
[2015-04-20 17:41:35,602][DEBUG][river.cluster            ] [Ectokid] processing [reroute_rivers_node_changed]: execute
[2015-04-20 17:41:35,602][DEBUG][river.cluster            ] [Ectokid] processing [reroute_rivers_node_changed]: no change in cluster_state
[2015-04-20 17:41:35,615][DEBUG][river                    ] [Ectokid] failed to (double) delete river [test5] content
org.elasticsearch.indices.TypeMissingException: [_all] type[[test5]] missing: No index has the type.
        at org.elasticsearch.action.admin.indices.mapping.delete.TransportDeleteMappingAction$1.onResponse(TransportDeleteMappingAction.java:138)
        at org.elasticsearch.action.admin.indices.mapping.delete.TransportDeleteMappingAction$1.onResponse(TransportDeleteMappingAction.java:117)
        at org.elasticsearch.action.support.broadcast.TransportBroadcastOperationAction$AsyncBroadcastAction.finishHim(TransportBroadcastOperationAction.java:252)
        at org.elasticsearch.action.support.broadcast.TransportBroadcastOperationAction$AsyncBroadcastAction.onOperation(TransportBroadcastOperationAction.java:217)
        at org.elasticsearch.action.support.broadcast.TransportBroadcastOperationAction$AsyncBroadcastAction$2.handleResponse(TransportBroadcastOperationAction.java:196)
        at org.elasticsearch.action.support.broadcast.TransportBroadcastOperationAction$AsyncBroadcastAction$2.handleResponse(TransportBroadcastOperationAction.java:183)
        at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:161)
        at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:130)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by jprante** [comment]
Do not worry, "double delete" message is not harmful.

**Comment by loganbhardy** [comment]
Thanks @jprante 

I still believe there is a scenario where this breaks down but it's intermittent and difficult to duplicate. I'll close the issue for now and re-open it when I have more information.
