### ISSUE TITLE
-Dlog4j.configurationFile=${bin}/log4j2.xml  is always reported wrong,TKS!

### ISSUE THREAD

**Issue by guyajun** [jprante/elasticsearch-jdbc#562]
ERROR StatusLogger Invalid URL c:/elasticsearch-jdbc-1.6.0.0-dist/elasticsearch-
jdbc-1.6.0.0/bin/log4j2.xml java.net.MalformedURLException: unknown protocol: c
        at java.net.URL.<init>(URL.java:593)
        at java.net.URL.<init>(URL.java:483)
        at java.net.URL.<init>(URL.java:432)
        at java.net.URI.toURL(URI.java:1089)
        at org.apache.logging.log4j.core.config.ConfigurationFactory.getInputFro
mUri(ConfigurationFactory.java:296)
        at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.get
Configuration(ConfigurationFactory.java:395)
        at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfigur
ation(ConfigurationFactory.java:254)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext
.java:419)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:
138)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log
4jContextFactory.java:207)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log
4jContextFactory.java:41)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:160)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:492)
        at org.xbib.tools.Importer.<clinit>(Importer.java:61)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.xbib.tools.Runner.main(Runner.java:25)

**Comment by guyajun** [comment]
I am upset with the URL problem！Thank you!

**Comment by jprante** [comment]
This is Windows problem, please add file:// to the `log4j.configurationFile` parameter, like this

```
 -Dlog4j.configurationFile=file://${bin}/log4j2.xml \
```
I can not test on Windows, so maybe other things are broken. I am grateful for working examples.

**Comment by guyajun** [comment]
Thanks ,you are handsome!

**Comment by danieljue** [comment]
I can confirm in Windows 7 that setting the parameter to 
-Dlog4j.configurationFile="file://%BIN%/log4j2.xml"
in the batch file does fix the logging error.

**Comment by guyajun** [comment]
Thank you very much!

**Comment by danieljue** [comment]
Actually, I'm sorry, I have to edit my confirmation -- it said logging was going fine but then it crapped out and gave a similar error.  It seems that %BIN% is being set to "%DIR%\..\bin\*" and the  "*" is messing up the path to the log4j file. 

 I finally seemed to have gotten around it by using an explicit path like 

"file://c:\esplugins\something\bin\log4j2.xml"

**Comment by guyajun** [comment]
Oh, You are a kind-hearted person. Well,Did you solve this problem. I search many talks, most of them says that there is no answers to it. TKS!
http://stackoverflow.com/questions/21260086/elasticsearch-river-jdbc-mysql-not-deleting-records

**Comment by danieljue** [comment]
It seems that the jdbc river setups are not really being tested on Windows platforms--I still couldn't get the river to work no matter where I put the jars or even having the classpath explicitly include them. (outside the scope of this ticket, for sure)  Next I'll try it inside a linux vm and see if things work better.

**Comment by koushikckm** [comment]
Thats solves!!! Thnx
