### ISSUE TITLE
NoClassSettingsException[Failed to load class with value [jdbc]

### ISSUE THREAD

**Issue by ouero** [jprante/elasticsearch-jdbc#569]
Elasticsearch version 1.6.0,Importer version 1.6.0.0,java version "1.7.0_67", Mysql version 5.4,on  win7 x64. 
I installed the JDBC plugin and copy the "mysql-connector-java-5.1.33.jar" to es lib . 
restart es.

[2015-06-18 09:24:27,176][WARN ][river                    ] [Tremolo] failed to create river [jdbc][who_jdbc_river]
org.elasticsearch.common.settings.NoClassSettingsException: Failed to load class with value [jdbc]
	at org.elasticsearch.river.RiverModule.loadTypeModule(RiverModule.java:87)
	at org.elasticsearch.river.RiverModule.spawnModules(RiverModule.java:58)
	at org.elasticsearch.common.inject.ModulesBuilder.add(ModulesBuilder.java:44)
	at org.elasticsearch.river.RiversService.createRiver(RiversService.java:138)
	at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:274)
	at org.elasticsearch.river.RiversService$ApplyRivers$2.onResponse(RiversService.java:268)
	at org.elasticsearch.action.support.TransportAction$ThreadedActionListener$1.run(TransportAction.java:113)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: jdbc
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.elasticsearch.river.RiverModule.loadTypeModule(RiverModule.java:73)
	... 9 more

**Comment by liutwv** [comment]
I got the same issue. 
It works fine with elasticsearch 1.5.2 and 1.5.2 jdbc plugin.
