### ISSUE TITLE
Issue "exception caught on transport layer"

### ISSUE THREAD

**Issue by Glecun** [jprante/elasticsearch-jdbc#577]
Sorry for my english, i'm french ;)

Before, I was using the version 1.4.4 of elasticSearch, but now I updated to the 1.6.0 version.
I was using River but i saw that it is deprecated now.

So, I tried to follow your tutorial but when I run my script there is this exception:
```
[2015-06-23 17:39:50,728][WARN ][transport.netty] [SuperMasterChief] exception caught on transport layer [[id: 0x945b45ba, /127.0.0.1:49275 => /127.0.0.1:9300]], closing connection
java.io.IOException: Une connexion existante a dû être fermée par l’hôte distant
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
I read that it is maybe because of some versions problems but I downloaded the elasticsearch-jdbc-1.6.0.0 and my only node is running with the version 1.6.0 of elasticsearch...
I am using the java version "1.8.0_45"

**Comment by Glecun** [comment]
Ok, i think i found the solution.
I forgot to specify the cluster name on my script, sorry for that.

**Comment by lferro9000** [comment]
I had exactly this issue on ubuntu and it turned out to be that elasticsearch was not enabled on /etc/default/elasticsearch configuration file. This issue was on a "default" graylog2 setup.
