### ISSUE TITLE
Old option not working

### ISSUE THREAD

**Issue by Glecun** [jprante/elasticsearch-jdbc#579]
Hi,

I was using river and the 1.4.4 version of elasticSearch with this type of script:
```
{
	"type" : "jdbc",
	"jdbc" : 
	[ {
		"url" : "jdbc:postgresql://'...",
		"user" : "user",
		"password" : "",
		"sql" : "...",
		"index" : "index1",
		"type" : "type1"
	}, {
		"url" : "jdbc:postgresql://'...",
		"user" : "user",
		"password" : "",
		"sql" : "...",
		"index" : "index2",
		"type" : "type2"
	} ] 
}
' | java \
    -cp "${lib}/*" \
    -Dlog4j.configurationFile=file://C:/Users/fr115484/Desktop/elasticsearch-jdbc-1.6.0.0/bin/log4j2.xml \
    org.xbib.tools.Runner \
    org.xbib.tools.JDBCImporter
```

Now I updated to the 1.6.0 version and I have this error:
```
[09:55:06,610][INFO ][BaseIngestTransportClient][pool-2-thread-1] index jdbc created
[09:55:06,748][ERROR][importer.jdbc.context.standard][pool-2-thread-1] java.lang.IllegalArgumentException: no SQL found
java.io.IOException: java.lang.IllegalArgumentException: no SQL found
	at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSource.fetch(StandardSource.java:617) ~[elasticsearch-jdbc-1.6.0.0-uberjar.jar:?]
	at org.xbib.elasticsearch.jdbc.strategy.standard.StandardContext.fetch(StandardContext.java:215) [elasticsearch-jdbc-1.6.0.0-uberjar.jar:?]
	at org.xbib.elasticsearch.jdbc.strategy.standard.StandardContext.execute(StandardContext.java:190) [elasticsearch-jdbc-1.6.0.0-uberjar.jar:?]
	at org.xbib.tools.JDBCImporter.process(JDBCImporter.java:117) [elasticsearch-jdbc-1.6.0.0-uberjar.jar:?]
	at org.xbib.tools.Importer.newRequest(Importer.java:241) [elasticsearch-jdbc-1.6.0.0-uberjar.jar:?]
	at org.xbib.tools.Importer.newRequest(Importer.java:57) [elasticsearch-jdbc-1.6.0.0-uberjar.jar:?]
	at org.xbib.pipeline.AbstractPipeline.call(AbstractPipeline.java:86) [elasticsearch-jdbc-1.6.0.0-uberjar.jar:?]
	at org.xbib.pipeline.AbstractPipeline.call(AbstractPipeline.java:17) [elasticsearch-jdbc-1.6.0.0-uberjar.jar:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_45]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.IllegalArgumentException: no SQL found
	at org.xbib.elasticsearch.common.util.SQLCommand.isQuery(SQLCommand.java:94) ~[elasticsearch-jdbc-1.6.0.0-uberjar.jar:?]
	at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSource.execute(StandardSource.java:652) ~[elasticsearch-jdbc-1.6.0.0-uberjar.jar:?]
	at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSource.fetch(StandardSource.java:583) ~[elasticsearch-jdbc-1.6.0.0-uberjar.jar:?]
	... 11 more
```

I think he cannot parse it :( please how can i correct or substitute that ?

Thanks

**Comment by feaster83** [comment]
He cannot parse that configuration because you are using a json array at the wrong level. 

You can use 2 parameters or 2 simple SQL commands. Examples:

```
{
    "type" : "jdbc",
    "jdbc" : {
        "url" : "jdbc:postgresql://'...",
        "user" : "user",
        "password" : "",
        "sql" : [ "select 'index1' _index, 'type1' _type, c.* from exampletable1 c",
                  "select 'index2' _index, 'type2' _type, d.* from exampletable2 d" ] 
    }
}
```
or 

```
{
    "type" : "jdbc",
    "jdbc" : {
        "url" : "jdbc:postgresql://'...",
        "user" : "user",
        "password" : "",
        "sql" : [ {
                  "statement":   "select 'index1' _index, 'type1' _type, c.* from exampletable1 c",
                  "parameter":   ...       
               },
                   "statement":   "select 'index2' _index, 'type2' _type, d.* from exampletable2 d",
                   "parameter":   ...       
               }] 
    }
}
```

**Comment by Glecun** [comment]
Thank you ! 
I hope it will work now :+1:
