### ISSUE TITLE
How I do elasticsearch-jdbc with SSL

### ISSUE THREAD

**Issue by alisarioglu** [jprante/elasticsearch-jdbc#585]
Hi All,
I've configured SSL on my node. Now I'm trying to create some indicies from a database with elasticsearch-jdbc and receive a lot of SSL and shield error messages. As I understand it right, I can turn off SSL for the transport client, so my access via elasticsearch-jdbc would be succesfull. 
But if I want to use SSL also for the transport client (elasticsearch-jdbc), 
How I do that? 
Is it possible?

Thanks and best wishes, Ali Sarioglu

**Comment by jprante** [comment]
Shield does not support JDBC river.

**Comment by alisarioglu** [comment]
Thanks a lot for the quick answer. 

I try to use just the import without the river or feeder configuration.

Only start the script with Runner and JDBCImporter

	#!/bin/sh

	JDBC_IMPORTER_HOME=/usr/share/elasticsearch/elasticsearch-jdbc-1.6.0.0
	bin=$JDBC_IMPORTER_HOME/bin
	lib=$JDBC_IMPORTER_HOME/lib

	/usr/lib/jvm/java-8-oracle/bin/java \
		-cp "${lib}/*" \
		-Dlog4j.configurationFile=${bin}/log4j2.xml \
		org.xbib.tools.Runner \
		org.xbib.tools.JDBCImporter \
		sms_dw.beitrag.json

And following json file

	{
		"elasticsearch":{
			"name" : "elasticsearch",
			"host" : "localhost",
			"port" : "9300",
			"client.type" : "tranpsort",
			"client.transport.ping_timeout" : "500s",
			"client.transport.node_sampler_interval" : "10s"
		},
		"type" : "jdbc",
		"jdbc" : {
			"driver" : "com.mysql.jdbc.Driver",
			"url" : "jdbc:mysql://localhost:3306/sms_dw",
			"user" : "user",
			"password" : "**********",
			"sql" :  "select *, id as _id from beitrag",
			"index" : "sms",
			"type" : "beitrag",
			"elasticsearch.autodiscover" : "true",
			"elasticsearch.host" : "hostname",
			"statefile" : "statefile.json"
		}
	}

SSL is turned off for transport

          "transport" : {
            "ssl" : "false"
          }

but still receive "no cluster nodes available"

	18:47,656][DEBUG][org.elasticsearch.transport.netty][pool-2-thread-1] [importer] disconnecting from [[#transport#-1][ip-172-31-31-252][inet[localhost/127.0.0.1:9300]]] due to explicit disconnect call
	[14:18:47,659][TRACE][org.elasticsearch.transport.netty][pool-2-thread-1] [importer] disconnected from [[#transport#-1][ip-172-31-31-252][inet[localhost/127.0.0.1:9300]]] due to explicit disconnect call
	[14:18:47,660][DEBUG][importer.jdbc.context.standard][pool-2-thread-1] after fetch
	[14:18:47,676][INFO ][importer.jdbc.context.standard][pool-2-thread-1] state persisted to statefile.json
	[14:18:47,676][DEBUG][importer.jdbc.source.standard][pool-2-thread-1] shutdown
	[14:18:47,677][DEBUG][importer.jdbc.source.standard][pool-2-thread-1] read connection closed
	[14:18:47,677][DEBUG][importer.jdbc.source.standard][pool-2-thread-1] write connection closed
	[14:18:47,678][ERROR][importer                 ][pool-2-thread-1] error while getting next input: no cluster nodes available, check settings {cluster.name=elasticsearch, host.0=localhost, port=9300, sniff=false, autodiscover=true, name=importer, client.transport.ignore_cluster_name=false, client.transport.ping_timeout=5s, client.transport.nodes_sampler_interval=5s}
	org.elasticsearch.client.transport.NoNodeAvailableException: no cluster nodes available, check settings {cluster.name=elasticsearch, host.0=localhost, port=9300, sniff=false, autodiscover=true, name=importer, client.transport.ignore_cluster_name=false, client.transport.ping_timeout=5s, client.transport.nodes_sampler_interval=5s}
		at org.xbib.elasticsearch.support.client.BaseTransportClient.createClient(BaseTransportClient.java:53) ~[elasticsearch-jdbc-1.6.0.0-uberjar.jar:?]
		at org.xbib.elasticsearch.support.client.BaseIngestTransportClient.newClient(BaseIngestTransportClient.java:22) ~[elasticsearch-jdbc-1.6.0.0-uberjar.jar:?]
		at org.xbib.elasticsearch.support.client.transport.BulkTransportClient.newClient(BulkTransportClient.java:88) ~[elasticsearch-jdbc-1.6.0.0-uberjar.jar:?]
		at org.xbib.elasticsearch.jdbc.strategy.standard.StandardContext$1.create(StandardContext.java:440) ~[elasticsearch-jdbc-1.6.0.0-uberjar.jar:?]
		at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSink.beforeFetch(StandardSink.java:94) ~[elasticsearch-jdbc-1.6.0.0-uberjar.jar:?]
		at org.xbib.elasticsearch.jdbc.strategy.standard.StandardContext.beforeFetch(StandardContext.java:207) ~[elasticsearch-jdbc-1.6.0.0-uberjar.jar:?]
		at org.xbib.elasticsearch.jdbc.strategy.standard.StandardContext.execute(StandardContext.java:188) ~[elasticsearch-jdbc-1.6.0.0-uberjar.jar:?]
		at org.xbib.tools.JDBCImporter.process(JDBCImporter.java:117) ~[elasticsearch-jdbc-1.6.0.0-uberjar.jar:?]
		at org.xbib.tools.Importer.newRequest(Importer.java:241) [elasticsearch-jdbc-1.6.0.0-uberjar.jar:?]
		at org.xbib.tools.Importer.newRequest(Importer.java:57) [elasticsearch-jdbc-1.6.0.0-uberjar.jar:?]
		at org.xbib.pipeline.AbstractPipeline.call(AbstractPipeline.java:86) [elasticsearch-jdbc-1.6.0.0-uberjar.jar:?]
		at org.xbib.pipeline.AbstractPipeline.call(AbstractPipeline.java:17) [elasticsearch-jdbc-1.6.0.0-uberjar.jar:?]
		at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
		at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
	[14:18:47,678][DEBUG][importer                 ][pool-2-thread-1] close (no op)
	[14:18:47,679][DEBUG][importer                 ][main] execution completed
	[14:18:47,679][DEBUG][importer                 ][main] cleanup (no op)

Thanks and best wishes, Ali

**Comment by alisarioglu** [comment]
To run the jdbc importer, Shield have to be deinstalled!

**Comment by wswuai** [comment]
Why shouldn't we support JDBC with Shield?

**Comment by jprante** [comment]
The problem is not JDBC. JDBC importer uses ES transport client. Shield uses special ES transport client and does not accept normal ES transport client.
