### ISSUE TITLE
org.elasticsearch.indices.IndexAlreadyExistsException

### ISSUE THREAD

**Issue by JerryPan** [jprante/elasticsearch-jdbc#593]
When I restart the importer, I often get this exception on output, why?  It seems wanting to create the index when this happens - if this behavior is expected, maybe it should be an INFO level message, not an ERROR?

**Comment by jprante** [comment]
What is the message?

**Comment by jprante** [comment]
JDBC importer checks for the existence of the configured index and only creates an index if it does not exist.

**Comment by JerryPan** [comment]
The message  is copied below - before I restart the importer, I did a delete index from commandline of the index "default", was trying to test the importer

==========================
[wlp:server] 10:44:39.729 [pool-6-thread-1] ERROR importer - error while getting next input: [default] al
ready exists
[wlp:server] org.elasticsearch.indices.IndexAlreadyExistsException: [default] already exists
[wlp:server]    at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validateIndexName(MetaDa
taCreateIndexService.java:160) ~[?:?]
[wlp:server]    at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validate(MetaDataCreateI
ndexService.java:551) ~[?:?]
[wlp:server]    at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.access$200(MetaDataCreat
eIndexService.java:88) ~[?:?]
[wlp:server]    at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreate
IndexService.java:230) ~[?:?]
[wlp:server]    at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalCluste
rService.java:374) ~[?:?]
[wlp:server]    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPr
ioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:188) ~[?:?]
[wlp:server]    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPr
ioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:158) ~[?:?]
[wlp:server]    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153) [?:1.8
.0]
[wlp:server]    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:1.8
.0]
[wlp:server]    at java.lang.Thread.run(Thread.java:785) [?:1.8.0]

**Comment by jprante** [comment]
Never saw such a message. How can I reproduce?

**Comment by JerryPan** [comment]
I have an embededed ES in a web server (wlp), and the JDBC Importer is configured as a contex listener to the ES servlet. Now I relaize the stack trace is probably from the ES side, if so I guess nothing should be done on the Importer side?

**Comment by jprante** [comment]
It does not matter how you run importer. The importer received the message from the cluster and reports it. But if there was no index of that name, there is nothing to complain that it exists, except the importer runs the index creation concurrently, which I don't know. So I have too few information to understand the error. Please write the steps you performed.
