### ISSUE TITLE
outofmemory when using sql parameter

### ISSUE THREAD

**Issue by abo** [jprante/elasticsearch-jdbc#643]
importer config:

```
{
    "type" : "jdbc",
    "jdbc" : {
        "url" : "jdbc:mysql://172.31.3.91:3306/webcastingraw",
        "user" : "user",
        "password" : "pwd",
        "sql" : [{
            "statement": "select * from userstat where join_time >= ?",
            "parameter": ["2015-07-01 00:00:00"]
            }],
        "index": "webcastingraw",
        "type": "userstat1"
    }
}
```

ERROR in log:

```
[11:33:30,934][ERROR][importer.jdbc.context.standard][pool-2-thread-1] Java heap space
java.lang.OutOfMemoryError: Java heap space
	at com.mysql.jdbc.MysqlIO.nextRowFast(MysqlIO.java:2114) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.MysqlIO.nextRow(MysqlIO.java:1921) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.MysqlIO.readSingleRowSet(MysqlIO.java:3278) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:462) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:2997) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:2245) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2638) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1907) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2030) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSource.executeQuery(StandardSource.java:934) ~[elasticsearch-jdbc-1.7.0.1-uberjar.jar:?]
	at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSource.executeWithParameter(StandardSource.java:704) ~[elasticsearch-jdbc-1.7.0.1-uberjar.jar:?]
	at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSource.fetch(StandardSource.java:580) ~[elasticsearch-jdbc-1.7.0.1-uberjar.jar:?]
	at org.xbib.elasticsearch.jdbc.strategy.standard.StandardContext.fetch(StandardContext.java:215) [elasticsearch-jdbc-1.7.0.1-uberjar.jar:?]
	at org.xbib.elasticsearch.jdbc.strategy.standard.StandardContext.execute(StandardContext.java:190) [elasticsearch-jdbc-1.7.0.1-uberjar.jar:?]
	at org.xbib.tools.JDBCImporter.process(JDBCImporter.java:118) [elasticsearch-jdbc-1.7.0.1-uberjar.jar:?]
	at org.xbib.tools.Importer.newRequest(Importer.java:241) [elasticsearch-jdbc-1.7.0.1-uberjar.jar:?]
	at org.xbib.tools.Importer.newRequest(Importer.java:57) [elasticsearch-jdbc-1.7.0.1-uberjar.jar:?]
	at org.xbib.pipeline.AbstractPipeline.call(AbstractPipeline.java:86) [elasticsearch-jdbc-1.7.0.1-uberjar.jar:?]
	at org.xbib.pipeline.AbstractPipeline.call(AbstractPipeline.java:17) [elasticsearch-jdbc-1.7.0.1-uberjar.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

```

when change to:

```
{
    "type" : "jdbc",
    "jdbc" : {
        "url" : "jdbc:mysql://172.31.3.91:3306/webcastingraw",
        "user" : "user",
        "password" : "pwd",
        "sql" : "select * from userstat where join_time >= '2015-07-01 00:00:00'",
        "index": "webcastingraw",
        "type": "userstat1"
    }
}
```
everything is correct

**Comment by abo** [comment]
http://stackoverflow.com/a/2448019

PreparedStatement streaming resultset not work ?

**Comment by abo** [comment]
my fault,

```
"resultset_concurrency":"CONCUR_READ_ONLY"
```

it works

**Comment by jprante** [comment]
Cool, thanks for the solution.
