### ISSUE TITLE
Hello world example throws an error

### ISSUE THREAD

**Issue by eddiejaoude** [jprante/elasticsearch-jdbc#644]
Hi, I am just trying to do a simple example using this plugin, but I get the following error. 

What am I doing wrong or missing in the config?

I think this is the error...

```bash
Message not fully read (response) for [0] handler future
```

More of the log...

```bash
[13:50:17,026][INFO ][importer.jdbc            ][pool-2-thread-1] strategy standard: settings = {password=xxxx, user=yyyyy, index_settings.index.number_of_shards=10, sql=select * from ags_files.proj, url=jdbc:postgresql://192.168.56.50:5432/ucims_importer?loglevel=0}, context = org.xbib.elasticsearch.jdbc.strategy.standard.StandardContext@3e51ee7e
[13:50:17,029][INFO ][importer.jdbc.context.standard][pool-2-thread-1] found sink class org.xbib.elasticsearch.jdbc.strategy.standard.StandardSink@48dcfee7
[13:50:17,034][INFO ][importer.jdbc.context.standard][pool-2-thread-1] found source class org.xbib.elasticsearch.jdbc.strategy.standard.StandardSource@1cf36c06
[13:50:17,057][INFO ][BaseTransportClient      ][pool-2-thread-1] creating transport client, java version 1.8.0_60, effective settings {cluster.name=elasticsearch, port=9300, sniff=false, autodiscover=false, name=importer, client.transport.ignore_cluster_name=false, client.transport.ping_timeout=5s, client.transport.nodes_sampler_interval=5s}
[13:50:17,089][INFO ][org.elasticsearch.plugins][pool-2-thread-1] [importer] loaded [support-1.5.2.2-c1cc89e], sites []
[13:50:17,551][INFO ][BaseTransportClient      ][pool-2-thread-1] trying to connect to [inet[localhost/127.0.0.1:9300]]
[13:50:17,674][WARN ][org.elasticsearch.transport.netty][elasticsearch[importer][transport_client_worker][T#1]{New I/O worker #1}] [importer] Message not fully read (response) for [0] handler future(org.elasticsearch.client.transport.TransportClientNodesService$SimpleNodeSampler$1@35390e10), error [false], resetting
[13:50:17,674][INFO ][org.elasticsearch.client.transport][pool-2-thread-1] [importer] failed to get node info for [#transport#-1][vagrant-ubuntu-trusty-64][inet[localhost/127.0.0.1:9300]], disconnecting...
org.elasticsearch.transport.RemoteTransportException: Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.node.info.NodesInfoResponse]
Caused by: org.elasticsearch.transport.TransportSerializationException: Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.node.info.NodesInfoResponse]
	at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:155) ~[elasticsearch-jdbc-1.5.2.0-uberjar.jar:?]
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:130) ~[elasticsearch-jdbc-1.5.2.0-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[elasticsearch-jdbc-1.5.2.0-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[elasticsearch-jdbc-1.5.2.0-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.

...
```

**Comment by eddiejaoude** [comment]
My java version...

```bash
$ java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```

Elastic search version...

```javascript
{
"status": 200,
"name": "Iron Fist",
"cluster_name": "elasticsearch",
"version": {
"number": "1.7.1",
"build_hash": "b88f43fc40b0bcd7f173a1f9ee2e97816de80b19",
"build_timestamp": "2015-07-29T09:54:16Z",
"build_snapshot": false,
"lucene_version": "4.10.4"
},
"tagline": "You Know, for Search"
}
```

**Comment by 0x2Adr1** [comment]
Make sure to use the latest version of this plugin because installation note in README.md is outdated.
http://xbib.org/repository/org/xbib/elasticsearch/importer/elasticsearch-jdbc/

**Comment by eddiejaoude** [comment]
Thanks @0x2Adr1 . I have now moved to using **logstash** for this functionality.
