### ISSUE TITLE
"no cluster nodes available" when running JDBC Importer 1.6.0.1 against ES 1.6.2

### ISSUE THREAD

**Issue by dqduc** [jprante/elasticsearch-jdbc#666]
Is it a version compatible issue ?
I also tested with ES 1.6.0 and got same problem.
All the `elasticsearch` config is corrected I believe (`devcluster` is my cluster name).

```
{
    "type" : "jdbc",
    "jdbc" : {
        "url" : "jdbc:mysql://localhost:3306/devdb",
        "user" : "test",
        "password" : "test",
        "sql" :  "SELECT * FROM logs",
        "elasticsearch" : {
            "cluster": "devcluster",
            "host" : "127.0.0.1",
            "port" : 9200
        },
        "max_bulk_actions" : 20000,
        "max_concurrent_bulk_requests" : 10,
        "index" : "testdata",
        "type" : "mc",
        "metrics" : {
            "enabled" : true,
            "logger" : {
                "plain" : true,
                "json" : true
            },
            "interval" : "5s"
        }
    }
}
```
BTW Do you have plan to support 1.6.x branch?

**Comment by jprante** [comment]
You can not use port 9200. It's HTTP. Please use port 9300.

**Comment by dqduc** [comment]
Thanks for pointing out this. It worked with ES 1.6.0 now, but still no luck for ES 1.6.2.
Here's the logs, look like an incompatible issue:

```
[09:57:48,983][INFO ][org.elasticsearch.plugins][pool-2-thread-1] [importer] loaded [support-1.6.0.0-8e7ca71], sites []
[09:57:49,570][INFO ][BaseTransportClient      ][pool-2-thread-1] trying to connect to [inet[/127.0.0.1:9300]]
[09:57:49,637][WARN ][org.elasticsearch.transport.netty][elasticsearch[importer][transport_client_worker][T#1]{New I/O worker #1}] [importer] Message not fully read (response) for [0] handler future(org.elasticsearch.client.transport.TransportClientNodesService$SimpleNodeSampler$1@678a0759), error [false], resetting
[09:57:49,637][INFO ][org.elasticsearch.client.transport][pool-2-thread-1] [importer] failed to get node info for [#transport#-1][Backup-Laptop][inet[/127.0.0.1:9300]], disconnecting...
org.elasticsearch.transport.RemoteTransportException: Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.node.info.NodesInfoResponse]
Caused by: org.elasticsearch.transport.TransportSerializationException: Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.node.info.NodesInfoResponse]
	at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:157) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:132) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_31]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.lang.NoClassDefFoundError: org/apache/lucene/analysis/standard/StandardAnalyzer
	at org.elasticsearch.Version.fromId(Version.java:447) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.Version.readVersion(Version.java:247) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.cluster.node.DiscoveryNode.readFrom(DiscoveryNode.java:324) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.cluster.node.DiscoveryNode.readNode(DiscoveryNode.java:307) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.action.support.nodes.NodeOperationResponse.readFrom(NodeOperationResponse.java:54) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.action.admin.cluster.node.info.NodeInfo.readFrom(NodeInfo.java:200) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.action.admin.cluster.node.info.NodeInfo.readNodeInfo(NodeInfo.java:194) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.action.admin.cluster.node.info.NodesInfoResponse.readFrom(NodesInfoResponse.java:54) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:155) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:132) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_31]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_31]
Caused by: java.lang.ClassNotFoundException: org.apache.lucene.analysis.standard.StandardAnalyzer
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_31]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_31]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_31]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_31]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_31]
	at org.elasticsearch.Version.fromId(Version.java:447) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.Version.readVersion(Version.java:247) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.cluster.node.DiscoveryNode.readFrom(DiscoveryNode.java:324) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.cluster.node.DiscoveryNode.readNode(DiscoveryNode.java:307) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.action.support.nodes.NodeOperationResponse.readFrom(NodeOperationResponse.java:54) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.action.admin.cluster.node.info.NodeInfo.readFrom(NodeInfo.java:200) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.action.admin.cluster.node.info.NodeInfo.readNodeInfo(NodeInfo.java:194) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.action.admin.cluster.node.info.NodesInfoResponse.readFrom(NodesInfoResponse.java:54) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:155) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:132) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[elasticsearch-jdbc-1.6.0.1-uberjar.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_31]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_31]
```

**Comment by jprante** [comment]
Please add lucene jar to the classpath.

**Comment by dqduc** [comment]
It worked:  I added lucene-analyzers-common-4.10.4.jar, lucene-core-4.10.4.jar to lib folder then run the script again. Thanks for pointing it out.

Actually I have two version of ES in same machine, I tried to test by running ES 1.6.0, then run import script ==> worked. Then I stopped ES 1.6.0 and run ES 1.6.2 ==> errors like above logs.

Include lucene jar as your suggestion solved the problem.

**Comment by OmPrakash22** [comment]
I added lucene-analyzers-common-4.10.4.jar, lucene-core-4.10.4.jar to lib folder then run the script again. Thanks.
