### ISSUE TITLE
Provide support for ES 2.0

### ISSUE THREAD

**Issue by skundrik** [jprante/elasticsearch-jdbc#667]
At the moment connecting to ES 2.0 generates exception on server

java.lang.IllegalStateException: Message not fully read (request) for requestId [0], action [cluster/nodes/info], readerIndex [39] vs expected [57]; resetting
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:120)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jprante** [comment]
Yes, there is no release of JDBC importer for Elasticsearch 2.0 yet. I wait for the release of Elasticsearch 2.0

**Comment by skundrik** [comment]
Hopefully it's not going to take long now with the recent RC1 release. I reckon a couple of weeks.

**Comment by jprante** [comment]
I just pushed the required changes to master, if you want to work from source, you can try it out.

**Comment by manishanker** [comment]
Hey,

I am still facing this issue. Is this fixed in ES2.0 ?

I am trying Nutch 2.3 + ES 2.0 integration.

Regards
Manishanker

**Comment by pferrel** [comment]
Merely upgrading from 1.4.1 to 2.0 causes this to happen.

I used to have Elasticsearch 1.4.1 running on my dev machine in a cluster of one with the default config except for:

    network.host: 127.0.0.1
    cluster.name: elasticsearch_pat

Now when I launch ES 2.0 with this config and no old indexes, just the default data folder I get exactly the same error as above.

**Comment by pferrel** [comment]
I suspect the errors are coming from another process that is trying to use ES since the error does not occur when I stop those other processes. Is there something that was removed from the ES code like a JDBC driver mentioned above?

**Comment by jprante** [comment]
JDBC importer 2.0.0.1 is only compatible with ES 2.0.0

JDBC plugin for ES 1.4 is a different thing. Please do not mix versions.

**Comment by RyanZhu1024** [comment]
any updates for this issue? I'm facing the same problem and can't get es working. Is there any way to workaround? should I downgrade es? I'm using java 1.8, springboot 1.3.0

**Comment by jprante** [comment]
There is JDBC importer for ES 2.0.0 and ES 2.1.0 released.

**Comment by jmreymond** [comment]
same issue with ES 2.1
[2015-12-24 08:32:22,684][WARN ][transport.netty          ] [Elfqueen] exception caught on transport layer 
[[id: 0x2ebbad9a, /37.187.7.133:44300 => /62.210.192.145:9300]], closing connection
java.lang.IllegalStateException: Message not fully read (request) for requestId [0], action [cluster/nodes/
info], readerIndex [39] vs expected [57]; resetting
        at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.ja
va:120)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler
.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(Default
ChannelPipeline.java:791)

**Comment by jprante** [comment]
@jmreymond you must use JDBC importer 2.1.1.2 to connect to ES 2.1
