### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: java/util/concurrent/atomic/LongAdder

### ISSUE THREAD

**Issue by Mice73** [jprante/elasticsearch-jdbc#681]
Hi @jprante,
I've this problem too :(.
Do you know why?
Thanks a lot.
Massimo

-----

   at org.xbib.metrics.MeanMetric.<init>(MeanMetric.java:9) ~[elasticsearch-jdbc-2.0.0.0-uberjar.jar:?]
        at org.xbib.elasticsearch.support.client.Metric.<init>(Metric.java:16) ~[elasticsearch-jdbc-2.0.0.0-uberjar.jar:?]
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardContext.<clinit>(StandardContext.java:83) ~[elasticsearch-jdbc-2.0.0.0-uberjar.jar:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_91]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_91]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_91]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_91]
        at java.lang.Class.newInstance(Class.java:383) ~[?:1.7.0_91]
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:373) ~[?:1.7.0_91]
        at java.util.ServiceLoader$1.next(ServiceLoader.java:445) ~[?:1.7.0_91]
        at org.xbib.elasticsearch.common.util.StrategyLoader.newContext(StrategyLoader.java:41) ~[elasticsearch-jdbc-2.0.0.0-uberjar.jar:?]
        at org.xbib.tools.JDBCImporter.process(JDBCImporter.java:110) ~[elasticsearch-jdbc-2.0.0.0-uberjar.jar:?]
        at org.xbib.tools.Importer.newRequest(Importer.java:215) ~[elasticsearch-jdbc-2.0.0.0-uberjar.jar:?]
        at org.xbib.tools.Importer.newRequest(Importer.java:54) ~[elasticsearch-jdbc-2.0.0.0-uberjar.jar:?]
        at org.xbib.pipeline.AbstractPipeline.call(AbstractPipeline.java:50) ~[elasticsearch-jdbc-2.0.0.0-uberjar.jar:?]
        at org.xbib.pipeline.AbstractPipeline.call(AbstractPipeline.java:16) ~[elasticsearch-jdbc-2.0.0.0-uberjar.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~[?:1.7.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[?:1.7.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[?:1.7.0_91]
        at java.lang.Thread.run(Thread.java:745) ~[?:1.7.0_91]

**Comment by jprante** [comment]
Something went wrong with packaging, I will release a 2.0.0.1 version soon

**Comment by jprante** [comment]
Can you use Java 8?

**Comment by Mice73** [comment]
I'm using Java 1.7 but if you want I can change version to check.
Let me know.

Massimo

**Comment by Mice73** [comment]
Ok, java 8! 
Bests!

**Comment by jprante** [comment]
I pushed version 2.0.0.1 which is also usable with Java 7.

**Comment by Antoniossss** [comment]
So what about this issue? I must have Java7 on prod and got the exception ;(

**Comment by jprante** [comment]
@Antoniossss which version do you use?
