### ISSUE TITLE
Unable to initialize plugins

### ISSUE THREAD

**Issue by sanchescom** [jprante/elasticsearch-jdbc#688]
Hello! I can't solve the problem. Please help!

I installed elasticsearch 2.0.0 on windows 7x64, start service and everything ok. Next I extracted elasticsearch-jdbc 2.0.0.1 plugin and restart elasticsearch. And it didn't start.

elasticsearch.log

java.lang.IllegalStateException: Unable to initialize plugins
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:115)
	at org.elasticsearch.node.Node.<init>(Node.java:144)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:170)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Caused by: java.nio.file.NoSuchFileException: E:\elasticsearch\plugins\elasticsearch-jdbc-2.0.0.1\plugin-descriptor.properties
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:86)
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:306)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:112)

elasticsearch-service-x64-stderr.2015-11-04.log

Java HotSpot(TM) 64-Bit Server VM warning: Using the ParNew young collector with the Serial old collector is deprecated and will likely be removed in a future release
Exception in thread "main" ies
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:86)
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:306)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:112)
	at org.elasticsearch.node.Node.<init>(Node.java:144)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:170)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.

**Comment by jprante** [comment]
JDBC importer is not a plugin, it's a standalone application, see documentation.

Sorry I have no experience with Windows and bat files.

I plan to explore possibilities to get JDBC importer back into ES as a plugin for ease of use, but this will not happen before ES 2.2 release.

**Comment by sanchescom** [comment]
In this article is mislead? 
http://r2d2.cc/2015/08/05/elastic-search-on-windows-with-mysql-sql-server-2014-and-import-feeder/

**Comment by jprante** [comment]
Wow!

In the article you find how to use PowerShell to run JDBC importer on Windows. 

Is that answering your question?
