### ISSUE TITLE
JDBC Importer 2.0.0.0/1 "Unknown Transport" error for the FoundNettyTransport when connecting to Found running ES 2.0.

### ISSUE THREAD

**Issue by monster-hkim** [jprante/elasticsearch-jdbc#690]
I am getting the below "Unknown Transport" for the FoundNettyTransport when connecting to Found running ES 2.0 using the JDBC Importer 2.0.0.0/1.

[14:58:25,269][ERROR][importer.jdbc.sink.standard][pool-3-thread-1] ingest not properly build, shutting down ingest
java.lang.IllegalArgumentException: Unknown Transport [org.elasticsearch.transport.netty.FoundNettyTransport]
at org.elasticsearch.transport.TransportModule.configure(TransportModule.java:103) ~[elasticsearch-jdbc-2.0.0.1-uberjar.jar:?]
at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:61) ~[elasticsearch-jdbc-2.0.0.1-uberjar.jar:?]
at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:212) ~[elasticsearch-jdbc-2.0.0.1-uberjar.jar:?]
at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:84) ~[elasticsearch-jdbc-2.0.0.1-uberjar.jar:?]
at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:130) ~[elasticsearch-jdbc-2.0.0.1-uberjar.jar:?]
at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99) ~[elasticsearch-jdbc-2.0.0.1-uberjar.jar:?]
at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:93) ~[elasticsearch-jdbc-2.0.0.1-uberjar.jar:?]
at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70) ~[elasticsearch-jdbc-2.0.0.1-uberjar.jar:?]
at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:47) ~[elasticsearch-jdbc-2.0.0.1-uberjar.jar:?]
at org.elasticsearch.client.transport.TransportClient$Builder.build(TransportClient.java:147) ~[elasticsearch-jdbc-2.0.0.1-uberjar.jar:?]
at org.xbib.elasticsearch.support.client.BaseTransportClient.createClient(BaseTransportClient.java:55) ~[elasticsearch-jdbc-2.0.0.1-uberjar.jar:?]
at org.xbib.elasticsearch.support.client.BaseIngestTransportClient.init(BaseIngestTransportClient.java:27) ~[elasticsearch-jdbc-2.0.0.1-uberjar.jar:?]
at org.xbib.elasticsearch.support.client.transport.BulkTransportClient.init(BulkTransportClient.java:85) ~[elasticsearch-jdbc-2.0.0.1-uberjar.jar:?]
at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSink$1.create(StandardSink.java:375) [elasticsearch-jdbc-2.0.0.1-uberjar.jar:?]
at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSink.setContext(StandardSink.java:85) [elasticsearch-jdbc-2.0.0.1-uberjar.jar:?]
at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSink.setContext(StandardSink.java:48) [elasticsearch-jdbc-2.0.0.1-uberjar.jar:?]
at org.xbib.elasticsearch.jdbc.strategy.standard.StandardContext.beforeFetch(StandardContext.java:178) [elasticsearch-jdbc-2.0.0.1-uberjar.jar:?]
at org.xbib.elasticsearch.jdbc.strategy.standard.StandardContext.execute(StandardContext.java:162) [elasticsearch-jdbc-2.0.0.1-uberjar.jar:?]
at org.xbib.tools.JDBCImporter.process(JDBCImporter.java:116) [elasticsearch-jdbc-2.0.0.1-uberjar.jar:?]
at org.xbib.tools.Importer.newRequest(Importer.java:215) [elasticsearch-jdbc-2.0.0.1-uberjar.jar:?]
at org.xbib.tools.Importer.newRequest(Importer.java:54) [elasticsearch-jdbc-2.0.0.1-uberjar.jar:?]
at org.xbib.pipeline.AbstractPipeline.call(AbstractPipeline.java:50) [elasticsearch-jdbc-2.0.0.1-uberjar.jar:?]
at org.xbib.pipeline.AbstractPipeline.call(AbstractPipeline.java:16) [elasticsearch-jdbc-2.0.0.1-uberjar.jar:?]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_65]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_65]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_65]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
[14:58:25,278][WARN ][org.xbib.elasticsearch.support.client.transport.BulkTransportClient][pool-3-thread-1] no client
[14:58:25,278][WARN ][importer.jdbc.sink.standard][pool-3-thread-1] no ingest found
[14:58:31,077][WARN ][org.xbib.elasticsearch.support.client.transport.BulkTransportClient][Thread-1] no client

Thanks,
-hkim

**Comment by dimitris-athanasiou** [comment]
Was the same working with elasticsearch 1.x.x?

**Comment by jprante** [comment]
Found is no longer supported b JDBC importer.
