### ISSUE TITLE
Column index out of range

### ISSUE THREAD

**Issue by kioku** [jprante/elasticsearch-jdbc#696]
Hello

I'm seeing the attached exception when setting `prepare_resultset_metadata` to `true`.
The result is the same regardless of the settings, or the sql statement.

The version in use is 1.7.1, along with MySQL.

I encountered this issue while trying to use the `$row` query parameter, which seems to only want to take the value of the last row of the current result set.

```
[02:12:46,012][ERROR][importer.jdbc.context.standard][pool-2-thread-1] java.sql.SQLException: Column index out of range.
java.io.IOException: java.sql.SQLException: Column index out of range.
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSource.fetch(StandardSource.java:617) ~[elasticsearch-jdbc-1.7.1.0-uberjar.jar:?]
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardContext.fetch(StandardContext.java:215) [elasticsearch-jdbc-1.7.1.0-uberjar.jar:?]
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardContext.execute(StandardContext.java:190) [elasticsearch-jdbc-1.7.1.0-uberjar.jar:?]
        at org.xbib.tools.JDBCImporter.process(JDBCImporter.java:118) [elasticsearch-jdbc-1.7.1.0-uberjar.jar:?]
        at org.xbib.tools.Importer.newRequest(Importer.java:241) [elasticsearch-jdbc-1.7.1.0-uberjar.jar:?]
        at org.xbib.tools.Importer.newRequest(Importer.java:57) [elasticsearch-jdbc-1.7.1.0-uberjar.jar:?]
        at org.xbib.pipeline.AbstractPipeline.call(AbstractPipeline.java:86) [elasticsearch-jdbc-1.7.1.0-uberjar.jar:?]
        at org.xbib.pipeline.AbstractPipeline.call(AbstractPipeline.java:17) [elasticsearch-jdbc-1.7.1.0-uberjar.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_80]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_80]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_80]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
Caused by: java.sql.SQLException: Column index out of range.
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:996) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:924) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:870) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.ResultSetMetaData.getField(ResultSetMetaData.java:392) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.ResultSetMetaData.getCatalogName(ResultSetMetaData.java:98) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSource.prepare(StandardSource.java:1232) ~[elasticsearch-jdbc-1.7.1.0-uberjar.jar:?]
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSource.execute(StandardSource.java:668) ~[elasticsearch-jdbc-1.7.1.0-uberjar.jar:?]
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSource.fetch(StandardSource.java:583) ~[elasticsearch-jdbc-1.7.1.0-uberjar.jar:?]
        ... 11 more
```

Thanks!

**Comment by jprante** [comment]
Yes, `$row` does not work across result sets.

Can you show the JSON specification for reproduction? Thanks.

**Comment by kioku** [comment]
From my trials and errors the issue is independent of the other settings, so something as simple as the configuration below throw the out of range exception.
```json
{
    "type" : "jdbc",
    "jdbc" : {
        "url" : "url",
        "user" : "user",
        "password" : "pass",
        "index": "index",
        "type": "type",
        "elasticsearch.host" : "10.0.0.1",
        "elasticsearch.port" : "9300",
        "prepare_resultset_metadata": true,
        "sql": [
            {
                "statement": "SELECT KeyID FROM table WHERE constraints"
            },
            {
                "statement": "DELETE FROM table WHERE KeyID = ?",
                "parameter": ["$row.KeyID"]
            }
        ]
    }
}
```

Can I also ask you to shed some light on the usage of the `$row` variable, and the `prepare_resultset_metadata` setting?

At this moment I'm guessing the only reliable way to achieve what I'm trying to do above is to either use the `$job` parameter, or execution timestamps. Am I correct?

Thanks!

**Comment by kioku** [comment]
Closing as stale.

**Comment by wanghc85** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
