### ISSUE TITLE
Options for AWS ElasticSearch Service?

### ISSUE THREAD

**Issue by patrickcarlohickman** [jprante/elasticsearch-jdbc#697]
Currently, it doesn't seem like this project can work with the AWS hosted ElasticSearch Service. In their limitations section, they specifically mention:

"The service supports HTTP on port 80, but does not support TCP transport."

Because of this, when attempting to use this project with the AWS ES service, one gets a org.elasticsearch.client.transport.NoNodeAvailableException.

Is there a setup or configuration available to use the REST API instead of the TransportClient? If not, are there any plans for making this available?

**Comment by jprante** [comment]
Thanks for the hint.

Yes, I plan to add HTTP bulk client support in the next version.

**Comment by patrickcarlohickman** [comment]
Nice!

AWS uses ES 1.5.2. Will the intended solution be available on previous
branches/tags? Or, will the new version work with ES 1.5?

**Comment by jprante** [comment]
If you want JDBC importer for ES 1.5 I would have to make a backport of the importer style. Of course, I can do that.
I'm confident the bulk HTTP API has not changed between 1.5 and 2.0, but I'm not 100% sure.

**Comment by patrickcarlohickman** [comment]
I think it would be beneficial. Amazon specifically states they support ES 1.5.2, so anyone trying to use this project with the new AWS ElasticSearch service will probably attempt to use the 1.5 branch first.

Thanks!

**Comment by Rajan** [comment]
@jprante We're facing the same issue. Did you get a chance to make a backport of the importer style? Is there a hack or solution we can try? Thanks in advance.

**Comment by jprante** [comment]
I pushed out JDBC importer version 1.5.2.0 for Elasticsearch 1.5.2

http://xbib.org/repository/org/xbib/elasticsearch/importer/elasticsearch-jdbc/1.5.2.0/elasticsearch-jdbc-1.5.2.0-dist.zip

Please try out if it can work with AWS ES, I don't have access to it.

**Comment by kingster** [comment]
Hi

Tried out this version and I get 

```
[05:30:40,824][WARN ][org.elasticsearch.transport.netty][elasticsearch[importer][transport_client_worker][T#1]{New I/O worker #1}] [importer] exception caught on transport layer [[id: 0x83bc06f5, /111.11.8.102:33909 :> xxxxxxx.us-west-2.es.amazonaws.com/54.111.111.11:80]], closing connection
java.io.StreamCorruptedException: invalid internal transport message format, got (48,54,54,50)
	at org.elasticsearch.transport.netty.SizeHeaderFrameDecoder.decode(SizeHeaderFrameDecoder.java:47) ~[elasticsearch-jdbc-1.5.2.0-uberjar.jar:?]
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425) ~[elasticsearch-jdbc-1.5.2.0-uberjar.jar:?]
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDe...
```

Elastic Search Version

```json
{
  "status" : 200,
  "name" : "Living Monolith",
  "cluster_name" : "lorem",
  "version" : {
    "number" : "1.5.2",
    "build_hash" : "62ff9868b4c8a0c45860bebb259e21980778ab1c",
    "build_timestamp" : "2015-04-27T09:21:06Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

I will drop you an email with an aws node address so that you can try it also.

**Comment by jprante** [comment]
It looks like AWS is only supporting HTTP.

HTTP support for JDBC importer is work in progress. Please be patient.

**Comment by jury89** [comment]
Any news on the HTTP support for JDBC?

**Comment by shavo007** [comment]
Im trying to do this now myself!! I want to bulk index with jdbc importer to es service on aws which is 1.5.2. 

Any suggestions what I can do!?

**Comment by jprante** [comment]
You can always write your own JDBC importer by forking the code.

At the moment, HTTP is not that important for JDBC importer. Also, supporting ES 1.5.2 is awkward to me, it's an unsupported, unstable und outdated version. Maybe AWS can offer supported toolkits to customers who are paying them to get data imported from DB, or can switch to up-to-date ES 2+. I'm just writing code in my limited spare time and have no relationship and no interest in AWS.

**Comment by shavo007** [comment]
I appreciate the response mate. 

I understand that 1.5.2 is extremely old. Current version is 2.3.2 and is what i would prefer to use!

But currently I am doing a technical spike of aws managed service. From what i gather they are planning to update but not sure when that will happen. 

I will fork your repo and see  can i introduce jest.
