### ISSUE TITLE
org.elasticsearch.client.transport.NoNodeAvailableException

### ISSUE THREAD

**Issue by GloriaBing** [jprante/elasticsearch-jdbc#710]
[22:26:12,603][WARN ][org.elasticsearch.client.transport][pool-3-thread-1] [importer] node {#transport#-1}{127.0.0.1}{127.0.0.1:9300} not part of the cluster Cluster [elasticsearch], ignoring...
[22:26:12,627][ERROR][importer.jdbc.context.standard][pool-3-thread-1] ingest not properly build, shutting down ingest
org.elasticsearch.client.transport.NoNodeAvailableException: no cluster nodes available, check settings {autodiscover=true, client.transport.ignore_cluster_name=false, client.transport.nodes_sampler_interval=5s, client.transport.ping_timeout=5s, cluster.name=elasticsearch, host.0=127.0.0.1, name=importer, port=9300, sniff=false}
	at org.xbib.elasticsearch.support.client.BaseTransportClient.createClient(BaseTransportClient.java:59) ~[elasticsearch-jdbc-2.0.0.0-uberjar.jar:?]
	at org.xbib.elasticsearch.support.client.BaseIngestTransportClient.init(BaseIngestTransportClient.java:28) ~[elasticsearch-jdbc-2.0.0.0-uberjar.jar:?]
	at org.xbib.elasticsearch.support.client.transport.BulkTransportClient.init(BulkTransportClient.java:85) ~[elasticsearch-jdbc-2.0.0.0-uberjar.jar:?]
	at org.xbib.elasticsearch.jdbc.strategy.standard.StandardContext$1.create(StandardContext.java:443) [elasticsearch-jdbc-2.0.0.0-uberjar.jar:?]
	at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSink.beforeFetch(StandardSink.java:96) [elasticsearch-jdbc-2.0.0.0-uberjar.jar:?]
	at org.xbib.elasticsearch.jdbc.strategy.standard.StandardContext.beforeFetch(StandardContext.java:205) [elasticsearch-jdbc-2.0.0.0-uberjar.jar:?]
	at org.xbib.elasticsearch.jdbc.strategy.standard.StandardContext.execute(StandardContext.java:186) [elasticsearch-jdbc-2.0.0.0-uberjar.jar:?]
	at org.xbib.tools.JDBCImporter.process(JDBCImporter.java:116) [elasticsearch-jdbc-2.0.0.0-uberjar.jar:?]
	at org.xbib.tools.Importer.newRequest(Importer.java:215) [elasticsearch-jdbc-2.0.0.0-uberjar.jar:?]
	at org.xbib.tools.Importer.newRequest(Importer.java:54) [elasticsearch-jdbc-2.0.0.0-uberjar.jar:?]
	at org.xbib.pipeline.AbstractPipeline.call(AbstractPipeline.java:50) [elasticsearch-jdbc-2.0.0.0-uberjar.jar:?]
	at org.xbib.pipeline.AbstractPipeline.call(AbstractPipeline.java:16) [elasticsearch-jdbc-2.0.0.0-uberjar.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
[22:26:12,662][WARN ][importer.jdbc.sink.standard][pool-3-thread-1] no ingest found
[22:26:18,619][WARN ][org.xbib.elasticsearch.support.client.transport.BulkTransportClient][Thread-1] no client

**Comment by jprante** [comment]
You have to configure the cluster name (and the correct versions).
