### ISSUE TITLE
OOM error

### ISSUE THREAD

**Issue by ClaudeZhangPiki** [jprante/elasticsearch-jdbc#728]
I run a scheduler with 'schedule=0 0-59 0-23 ? * *'.
But,after 7 hours,OOM error happened ....
.
[pool-2-thread-1]
.......
[pool-4-thread-1]
.......
[pool-6-thread-1]
......
......
[05:13:00,022][ERROR][org.xbib.pipeline.AbstractPipeline][pool-834-thread-1] unable to create new native thread
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method) ~[?:1.7.0_91]
	at java.lang.Thread.start(Thread.java:714) ~[?:1.7.0_91]
	at org.elasticsearch.threadpool.ThreadPool.<init>(ThreadPool.java:255) ~[elasticsearch-jdbc-2.1.0.0-uberjar.jar:?]
	at org.elasticsearch.client.transport.TransportClient$Builder.build(TransportClient.java:130) ~[elasticsearch-jdbc-2.1.0.0-uberjar.jar:?]
	at org.xbib.elasticsearch.helper.client.BaseTransportClient.createClient(BaseTransportClient.java:50) ~[elasticsearch-jdbc-2.1.0.0-uberjar.jar:?]
	at org.xbib.elasticsearch.helper.client.BaseMetricTransportClient.init(BaseMetricTransportClient.java:27) ~[elasticsearch-jdbc-2.1.0.0-uberjar.jar:?]
	at org.xbib.elasticsearch.helper.client.transport.BulkTransportClient.init(BulkTransportClient.java:86) ~[elasticsearch-jdbc-2.1.0.0-uberjar.jar:?]
	at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSink$1.create(StandardSink.java:378) ~[elasticsearch-jdbc-2.1.0.0-uberjar.jar:?]
	at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSink.setContext(StandardSink.java:86) ~[elasticsearch-jdbc-2.1.0.0-uberjar.jar:?]
	at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSink.setContext(StandardSink.java:49) ~[elasticsearch-jdbc-2.1.0.0-uberjar.jar:?]
	at org.xbib.elasticsearch.jdbc.strategy.standard.StandardContext.beforeFetch(StandardContext.java:178) ~[elasticsearch-jdbc-2.1.0.0-uberjar.jar:?]
	at org.xbib.elasticsearch.jdbc.strategy.standard.StandardContext.execute(StandardContext.java:162) ~[elasticsearch-jdbc-2.1.0.0-uberjar.jar:?]
	at org.xbib.tools.JDBCImporter.process(JDBCImporter.java:116) ~[elasticsearch-jdbc-2.1.0.0-uberjar.jar:?]
	at org.xbib.tools.Importer.newRequest(Importer.java:215) ~[elasticsearch-jdbc-2.1.0.0-uberjar.jar:?]
	at org.xbib.tools.Importer.newRequest(Importer.java:54) ~[elasticsearch-jdbc-2.1.0.0-uberjar.jar:?]
	at org.xbib.pipeline.AbstractPipeline.call(AbstractPipeline.java:50) [elasticsearch-jdbc-2.1.0.0-uberjar.jar:?]
	at org.xbib.pipeline.AbstractPipeline.call(AbstractPipeline.java:16) [elasticsearch-jdbc-2.1.0.0-uberjar.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_91]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_91]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_91]
[05:18:00,005][ERROR][importer                 ][pool-2-thread-2] java.lang.OutOfMemoryError: unable to create new native thread

**Comment by ClaudeZhangPiki** [comment]
jere is my script.
#!/bin/sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
bin=${DIR}/../bin
lib=${DIR}/../lib

echo '{
  "type": "jdbc",
  "jdbc": {
    "url": "jdbc:mysql://10.10.10.12:3306/my_index",
    "user": "user",
    "password": "password",
    "sql": [
            {
                "statement": "select *,id as _id from my_type where mytimestamp > ?",
                "parameter": [
                    "$metrics.lastexecutionstart"
                ]
            }
        ] ,
    "index": "my_index",
    "type": "my_type",
    "flush_interval": "60s",
    "schedule": "0 0-59 0-23 ? * *",
	"elasticsearch.cluster": "mycluster",
	"elasticsearch.host": "10.10.10.11",
	"elasticsearch.port": "9300"
  }
}
' | java \
    -cp "${lib}/*" \
    -Dlog4j.configurationFile=${bin}/log4j2.xml \
    org.xbib.tools.Runner \
    org.xbib.tools.JDBCImporter

**Comment by jprante** [comment]
What is the output of `ulimit -a` for the user of JDBC importer?

**Comment by ClaudeZhangPiki** [comment]
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63560
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65536
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 10240
cpu time               (seconds, -t) unlimited
max user processes              (-u) 10240
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by jprante** [comment]
"max user processes" is ok.

TransportClient may go berserk with threads when connection got lost to the cluster.

You should restart JDBC importer in that case or disable sniff mode.

**Comment by ClaudeZhangPiki** [comment]
Yes,
I changed schedule as 'schedule=0 0/2 0-23 ? * *' and restarted importer .
now,importer runs more than 23 hours and it is still stable.
but sometime in the future, maybe 24 hours or more...will importer touch "max user processes" and report OOM error again?

**Comment by jprante** [comment]
This is not JDBC importer, but it may be the specific situation when ES cluster connection is not stable. Please watch log files of the cluster, if there are disconnections, or other problems, like resource usage.

**Comment by ClaudeZhangPiki** [comment]
OK,i got it..
I will check ES logs.
Thank you very much.
:)
