### ISSUE TITLE
Problem with date conversion from oracle to elastic search while migrating 

### ISSUE THREAD

**Issue by false9striker** [jprante/elasticsearch-jdbc#762]
By default elastic search converts date to long, so I'm trying the same while migrating existing data from oracle. 
Existing representation in oracle - "YYYY-mm-dd'T'HH24:mm:ss.SSS-08:00". Could you please help convert this to long. @jprante

**Comment by jprante** [comment]
Oracle stores timestamps as `DATE`, `TIMESTAMP`, `TIMESTAMP WITH TIME ZONE`, and `TIMESTAMP WITH LOCAL TIME ZONE`

https://docs.oracle.com/database/121/NLSPG/ch4datetime.htm#NLSPG004

With datetime, you can use a variety of formats to parse values, see https://www.elastic.co/guide/en/elasticsearch/reference/2.1/mapping-date-format.html

To format UTC timestamps, which are ES default, from Oracle dates, you can use an SQL statement like

```
select to_char(sys_extract_utc(from_tz(cast(my_date_column as timestamp),'Europe/Berlin')),'YYYY-MM-DD"T"HH24:MI:SS"Z"') as "date" from my_table
```

**Comment by false9striker** [comment]
Thank you so much for your reply. When I try the above solution I get NumberFormatException

```
"sql":"select  to_char(sys_extract_utc(from_tz(cast( my_date_column as timestamp),'"'"'Europe/Berlin'"'"')),'"'"'YYYY-MM-DD HH24:MI:SS'"'"')  as \"createdDate\" from my_table"
```
Removed 'T' and 'Z' as it was throwing error.

```
Caused by: java.lang.NumberFormatException: For input string: "2016-01-26 15:58:07"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:441)
	at java.lang.Long.parseLong(Long.java:483)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.longValue(AbstractXContentParser.java:145)
	at org.elasticsearch.index.mapper.core.LongFieldMapper.innerParseCreateField(LongFieldMapper.java:288)
	at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:239)
	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:401)
```

My problem is Elastic Search has mapping 'long' in a date field where as oracle has 'Date'. When I migrate I want oracle date field to be stored as long in Elastic Search.

**Comment by jprante** [comment]
You need 'T' and 'Z'. Use escape syntax for apostrophe.

**Comment by jprante** [comment]
You can not use `long` field, you must use ES `date` field, see https://www.elastic.co/guide/en/elasticsearch/reference/2.1/mapping-date-format.html

**Comment by false9striker** [comment]
Thanks let me try.
