### ISSUE TITLE
I cant start my elasticserch after move elasticsearch-jdbc/lib to lib

### ISSUE THREAD

**Issue by soloqi** [jprante/elasticsearch-jdbc#776]
error log：
[2016-02-29 06:34:35,816][ERROR][bootstrap                ] Exception
java.lang.IllegalStateException: jar hell!
class: org.elasticsearch.node.NodeClosedException
jar1: /usr/share/elasticsearch/lib/elasticsearch-2.2.0.jar
jar2: /usr/share/elasticsearch/lib/elasticsearch-jdbc-2.2.0.0-uberjar.jar
	at org.elasticsearch.bootstrap.JarHell.checkClass(JarHell.java:280)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:186)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:87)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:164)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
——————————————————————————————
please help me

**Comment by jprante** [comment]
You must not move JDBC importer to ES lib.

**Comment by soloqi** [comment]
thank you very much 
I just think it is work as seem as plugin before you tell me
forgive my poor English
^_^
