### ISSUE TITLE
elasticsearch-jdbc-2.3.1.0 Feeder Exception

### ISSUE THREAD

**Issue by sandesh2014** [jprante/elasticsearch-jdbc#805]
When i try to run the feeder it is throwing the below error:

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/xbib/tools/Runner : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by jprante** [comment]
Please use Java 8.

**Comment by hovanhon** [comment]
@jprante 
 >Please use Java 8.
because of I am used java 1.7_79, I don't want to exchange to 1.8. 
are there any solution for about problem?
thanks

**Comment by jprante** [comment]
There is no more support for Java 7 since April 2015

http://www.oracle.com/technetwork/java/eol-135779.html

I urge you to use Java 8.
