### ISSUE TITLE
Could not load plugin descriptor for existing plugin [elasticsearch-jdbc-2.3.3.0]

### ISSUE THREAD

**Issue by misterunknown** [jprante/elasticsearch-jdbc#844]
Hi,

I want to upgrade from ES 1.4.4 to ES 2.3.3. So I downloaded 2.3.3 and the corresponding JDBC plugin version (2.3.3) and unpacked it in the plugin directory. But when I try to start elasticsearch this error occurs:
```
Exception in thread "main" java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [elasticsearch-jdbc-2.3.3.0]. Was the plugin built before 2.0?
Likely root cause: java.nio.file.NoSuchFileException: /opt/elasticsearch/plugins/elasticsearch-jdbc-2.3.3.0/plugin-descriptor.properties
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:87)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:378)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:128)
        at org.elasticsearch.node.Node.<init>(Node.java:158)
        at org.elasticsearch.node.Node.<init>(Node.java:140)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.
```
The directory structure looks like this and contains no "plugin-descriptor.properties" at all:
```
/opt/elasticsearch/
+--plugins
   +--elasticsearch-jdbc-2.3.3.0
       +--bin
       +--lib
```
Any idea what I'm doing wrong?

Cheers,
Marco

**Comment by misterunknown** [comment]
Oh, read first, then ask. Sorry!
