### ISSUE TITLE
Consistently facing ORA-22922 while trying populate Elastic instance with Oracle DB data

### ISSUE THREAD

**Issue by sanaulla123** [jprante/elasticsearch-jdbc#866]
The below is the stack trace observer:

```
[08:52:46,504][ERROR][importer.jdbc.context.standard][pool-3-thread-1] at fetch: java.sql.SQLException: ORA-22922: nonexistent LOB value

java.io.IOException: java.sql.SQLException: ORA-22922: nonexistent LOB value

        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSource.fetch(StandardSource.java:631) ~[elasticsearch-jdbc-2.3.1.0.jar:?]
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardContext.fetch(StandardContext.java:191) [elasticsearch-jdbc-2.3.1.0.jar:?]
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardContext.execute(StandardContext.java:166) [elasticsearch-jdbc-2.3.1.0.jar:?]
        at org.xbib.tools.JDBCImporter.process(JDBCImporter.java:199) [elasticsearch-jdbc-2.3.1.0.jar:?]
        at org.xbib.tools.JDBCImporter.newRequest(JDBCImporter.java:185) [elasticsearch-jdbc-2.3.1.0.jar:?]
        at org.xbib.tools.JDBCImporter.newRequest(JDBCImporter.java:51) [elasticsearch-jdbc-2.3.1.0.jar:?]
        at org.xbib.pipeline.AbstractPipeline.call(AbstractPipeline.java:50) [elasticsearch-jdbc-2.3.1.0.jar:?]
        at org.xbib.pipeline.AbstractPipeline.call(AbstractPipeline.java:16) [elasticsearch-jdbc-2.3.1.0.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.sql.SQLException: ORA-22922: nonexistent LOB value

        at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:445) ~[ojdbc6-11.2.0.jar:11.2.0.3.0]
        at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:389) ~[ojdbc6-11.2.0.jar:11.2.0.3.0]
        at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:382) ~[ojdbc6-11.2.0.jar:11.2.0.3.0]
        at oracle.jdbc.driver.T4C8TTILob.processError(T4C8TTILob.java:792) ~[ojdbc6-11.2.0.jar:11.2.0.3.0]
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:450) ~[ojdbc6-11.2.0.jar:11.2.0.3.0]
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192) ~[ojdbc6-11.2.0.jar:11.2.0.3.0]
        at oracle.jdbc.driver.T4C8TTILob.freeTemporaryLob(T4C8TTILob.java:297) ~[ojdbc6-11.2.0.jar:11.2.0.3.0]
        at oracle.jdbc.driver.T4CConnection.freeTemporary(T4CConnection.java:3429) ~[ojdbc6-11.2.0.jar:11.2.0.3.0]
        at oracle.sql.CLOB.freeTemporary(CLOB.java:1044) ~[ojdbc6-11.2.0.jar:11.2.0.3.0]
        at oracle.sql.CLOB.free(CLOB.java:1823) ~[ojdbc6-11.2.0.jar:11.2.0.3.0]
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSource.parseType(StandardSource.java:1510) ~[elasticsearch-jdbc-2.3.1.0.jar:?]
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSource.processRow(StandardSource.java:1102) ~[elasticsearch-jdbc-2.3.1.0.jar:?]
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSource.nextRow(StandardSource.java:1065) ~[elasticsearch-jdbc-2.3.1.0.jar:?]
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSource.merge(StandardSource.java:801) ~[elasticsearch-jdbc-2.3.1.0.jar:?]
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSource.execute(StandardSource.java:689) ~[elasticsearch-jdbc-2.3.1.0.jar:?]
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSource.fetch(StandardSource.java:597) ~[elasticsearch-jdbc-2.3.1.0.jar:?]
        ... 11 more
```

I am using the defaults for all the JDBC Connection properties. 

The query which I am using takes around 7 minutes to execute. And after that I can see the data being moved from source to sink via the metrics logs. 

Please advise on how to resolve this issue?

**Comment by jprante** [comment]
Do you use transactions?

Can you show the SQL query and the table column definition of the LOB column?

**Comment by sanaulla123** [comment]
No, not using transactions. 

Its a complex query based on joining of views. where each view is derived from other views. The LOB under consideration is a CLOB

The max length of that CLOB (as computed by dbms_lob.getlength()) is 9411. 

It was consistently breaking at a given record id. 

And the latest run, the execution never went past:

```
[10:33:42,658][DEBUG][importer.jdbc.source.standard][pool-3-thread-1] org.xbib.elasticsearch.jdbc.strategy.standard.StandardSource@1ac1731f using read connection oracle.jdbc.driver.T4CConnection@4df4162e for executing query
[10:33:42,658][DEBUG][importer.jdbc.source.standard][pool-3-thread-1] org.xbib.elasticsearch.jdbc.strategy.standard.StandardSource@1ac1731f using read connection oracle.jdbc.driver.T4CConnection@4df4162e for executing query

```

I guess it has been stuck waiting for response from the DB for almost an hour.

**Comment by sanaulla123** [comment]
There were some active sessions which I have killed and restarted the import. Let me get back if it fails with the LOB exception at the same point

**Comment by sanaulla123** [comment]
the issue here was the SQL query timeout. We fixed the query to improve its performance and there by get rid of this problem.
