### ISSUE TITLE
how to import data when  escluster has install shield plugins

### ISSUE THREAD

**Issue by zhangzizhi** [jprante/elasticsearch-jdbc#874]
org.elasticsearch.transport.RemoteTransportException: [node-1][192.168.159.131:9300][cluster:monitor/nodes/liveness]
Caused by: org.elasticsearch.ElasticsearchSecurityException: missing authentication token for action [cluster:monitor/nodes/liveness]
        at org.elasticsearch.shield.support.Exceptions.authenticationError(Exceptions.java:39) ~[?:?]
        at org.elasticsearch.shield.authc.DefaultAuthenticationFailureHandler.missingToken(DefaultAuthenticationFailureHandler.java:70) ~[?:?]
        at org.elasticsearch.shield.authc.InternalAuthenticationService.authenticateWithRealms(InternalAuthenticationService.java:282) ~[?:?]
        at org.elasticsearch.shield.authc.InternalAuthenticationService.authenticate(InternalAuthenticationService.java:184) ~[?:?]
        at org.elasticsearch.shield.transport.ServerTransportFilter$NodeProfile.inbound(ServerTransportFilter.java:112) ~[?:?]
        at org.elasticsearch.shield.transport.ShieldServerTransportService$ProfileSecuredRequestHandler.messageReceived(ShieldServerTransportService.java:176) ~[?:?]

**Comment by jprante** [comment]
Shield plugin can not be supported, it is not open source.

**Comment by zhangzizhi** [comment]
thank you

**Comment by LoganDepp** [comment]
@jprante Hi, jprante. I remove shield first, then use es-jdbc to import data. And after I install shield back, when I use with head, I find that the _index I import use by es-jdbc is null! This is because of the shield?
