### ISSUE TITLE
after fetch : no such index

### ISSUE THREAD

**Issue by momsbaby** [jprante/elasticsearch-jdbc#876]
please tell me how to fix this error. I got no idea.

[17:50:27,486][INFO ][importer.jdbc.source.standard][pool-6-thread-1] execute sql is oracle.jdbc.driver.OraclePreparedStatementWrapper@279eed54 
[17:50:27,517][INFO ][importer.jdbc.context.standard][pool-6-thread-1] state persisted to truckstate.json
[17:50:27,522][ERROR][importer.jdbc.context.standard][pool-6-thread-1] after fetch: no such index
org.elasticsearch.index.IndexNotFoundException: no such index
    at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.resolve(IndexNameExpressionResolver.java:585) ~[elasticsearch-2.3.4.jar:2.3.4]
    at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:133) ~[elasticsearch-2.3.4.jar:2.3.4]
    at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:77) ~[elasticsearch-2.3.4.jar:2.3.4]
    at org.elasticsearch.action.support.replication.TransportBroadcastReplicationAction.shards(TransportBroadcastReplicationAction.java:131) ~[elasticsearch-2.3.4.jar:2.3.4]
    at org.elasticsearch.action.support.replication.TransportBroadcastReplicationAction.doExecute(TransportBroadcastReplicationAction.java:78) ~[elasticsearch-2.3.4.jar:2.3.4]
    at org.elasticsearch.action.support.replication.TransportBroadcastReplicationAction.doExecute(TransportBroadcastReplicationAction.java:56) ~[elasticsearch-2.3.4.jar:2.3.4]
    at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:137) ~[elasticsearch-2.3.4.jar:2.3.4]
    at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:61) ~[elasticsearch-2.3.4.jar:2.3.4]
    at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:51) ~[elasticsearch-2.3.4.jar:2.3.4]
    at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75) ~[elasticsearch-2.3.4.jar:2.3.4]
    at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:245) ~[elasticsearch-2.3.4.jar:2.3.4]
    at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:114) ~[elasticsearch-2.3.4.jar:2.3.4]
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.10.5.Final.jar:?]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.10.5.Final.jar:?]
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.10.5.Final.jar:?]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) ~[netty-3.10.5.Final.jar:?]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462) ~[netty-3.10.5.Final.jar:?]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443) ~[netty-3.10.5.Final.jar:?]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) ~[netty-3.10.5.Final.jar:?]
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.10.5.Final.jar:?]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.10.5.Final.jar:?]
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.10.5.Final.jar:?]
    at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75) ~[elasticsearch-2.3.4.jar:2.3.4]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.10.5.Final.jar:?]
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) ~[netty-3.10.5.Final.jar:?]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[netty-3.10.5.Final.jar:?]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[netty-3.10.5.Final.jar:?]
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[netty-3.10.5.Final.jar:?]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) ~[netty-3.10.5.Final.jar:?]
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) ~[netty-3.10.5.Final.jar:?]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) ~[netty-3.10.5.Final.jar:?]
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[netty-3.10.5.Final.jar:?]
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[netty-3.10.5.Final.jar:?]
    at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[netty-3.10.5.Final.jar:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.8.0_91]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.8.0_91]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

**Comment by momsbaby** [comment]
here is my config:
#!/bin/sh
bin=$JDBC_IMPORTER_HOME/bin
lib=$JDBC_IMPORTER_HOME/lib
echo '{
"type" : "jdbc",
"jdbc": {
"elasticsearch.autodiscover":true,
"elasticsearch.cluster":"TestEs",
"url":"jdbc:oracle:thin:@10.9.15.11:1521:devdb",
"user":"ztm",
"password":"shztmtest221%^#",
"sql":[{
"statement" :"select 'truck_' || to_char(truck_end_date,'YYYY-MM-DD') \"_index\",t.* from zto_truck t where t.modifiedon > ?",
"parameter" :["$metrics.lastexecutionstart"]
}],
"elasticsearch" : {
"host" : "10.9.15.35",
"port" : 9300
},
"statefile":"truckstate.json",
"schedule":"1 * * * * ?",
"type" : "truck"
}
}'| java \
-cp "${lib}/*" \
-Dlog4j.configurationFile=${bin}/log4j2.xml \
org.xbib.tools.Runner \
org.xbib.tools.JDBCImporter

Does elasticsearch-jdbc not support this? dynamic index..

**Comment by w84264423** [comment]
hi,I have encountered the same problem, you solve it?

**Comment by chandrupal** [comment]
I do have the same issue and no luck yet.

On a side note, to reproduce this error, I have tried setting up ES in two machines and changed the network.bind_host, then I got this issue and not fixed yet.

**Comment by jprante** [comment]
This is not JDBC importer, but Elasticsearch. During a replication, the index you want to write to does not exist. I can only speculate about the reasons, it looks like a bug during dynamic index creation and slow cluster state replication, where ES 2.x has known weaknesses. You can try without replica (and add replica after JDBC import) or pre-create the index before JDBC importer run.

**Comment by chandrupal** [comment]
@jprante Thanks for the details. I hope this will help me.
