### ISSUE TITLE
Problem with the jdbc import

### ISSUE THREAD

**Issue by xjpphp** [jprante/elasticsearch-jdbc#878]
Hi i'm having problems with the jdbc importer version 2.3.4.0.
This is my config file myscript.sh:
`echo '{
    "type" : "jdbc",

    "jdbc" : {
        "url" : "jdbc:mysql://localhost:3306/news",

        "user" : "",

        "password" : "",

        "schedule" : "* 0/1 * * * ?",

        "interval" : "1s",

        "sql" : "select *, id as _id from news",

        "index" : "test1"

 }
}' | java \

       -cp "${lib}/*" \

       -Dlog4j.configurationFile=${bin}/log4j2.xml \

       org.xbib.tools.Runner \

       org.xbib.tools.JDBCImporter
`

I get this error in the log file when I run script:

[ERROR][importer.jdbc            ][pool-606-thread-1] error while processing request: Failed to create a selector.
org.jboss.netty.channel.ChannelException: Failed to create a selector.
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.openSelector(AbstractNioSelector.java:362) ~[netty-3.10.5.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.<init>(AbstractNioSelector.java:100) ~[netty-3.10.5.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.<init>(AbstractNioWorker.java:52) ~[netty-3.10.5.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.NioWorker.<init>(NioWorker.java:45) ~[netty-3.10.5.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.NioWorkerPool.newWorker(NioWorkerPool.java:44) ~[netty-3.10.5.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.NioWorkerPool.newWorker(NioWorkerPool.java:28) ~[netty-3.10.5.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorkerPool.init(AbstractNioWorkerPool.java:80) ~[netty-3.10.5.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.NioWorkerPool.<init>(NioWorkerPool.java:39) ~[netty-3.10.5.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.NioWorkerPool.<init>(NioWorkerPool.java:33) ~[netty-3.10.5.Final.jar:?]
        at org.elasticsearch.transport.netty.NettyTransport.createClientBootstrap(NettyTransport.java:346) ~[elasticsearch-2.3.4.jar:2.3.4]
        at org.elasticsearch.transport.netty.NettyTransport.doStart(NettyTransport.java:279) ~[elasticsearch-2.3.4.jar:2.3.4]
        at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68) ~[elasticsearch-2.3.4.jar:2.3.4]
        at org.elasticsearch.transport.TransportService.doStart(TransportService.java:182) ~[elasticsearch-2.3.4.jar:2.3.4]
        at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68) ~[elasticsearch-2.3.4.jar:2.3.4]
        at org.xbib.elasticsearch.helper.client.TransportClient$Builder.build(TransportClient.java:139) ~[elasticsearch-helper-2.3.4.0.jar:?]
        at org.xbib.elasticsearch.helper.client.BaseTransportClient.createClient(BaseTransportClient.java:73) ~[elasticsearch-helper-2.3.4.0.jar:?]
        at org.xbib.elasticsearch.helper.client.BaseMetricTransportClient.init(BaseMetricTransportClient.java:40) ~[elasticsearch-helper-2.3.4.0.jar:?]
        at org.xbib.elasticsearch.helper.client.BulkTransportClient.init(BulkTransportClient.java:96) ~[elasticsearch-helper-2.3.4.0.jar:?]
        at org.xbib.elasticsearch.helper.client.ClientBuilder.toBulkTransportClient(ClientBuilder.java:113) ~[elasticsearch-helper-2.3.4.0.jar:?]
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSink.createClient(StandardSink.java:348) ~[elasticsearch-jdbc-2.3.4.0.jar:?]
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSink.beforeFetch(StandardSink.java:100) ~[elasticsearch-jdbc-2.3.4.0.jar:?]
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardContext.beforeFetch(StandardContext.java:183) ~[elasticsearch-jdbc-2.3.4.0.jar:?]
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardContext.execute(StandardContext.java:164) ~[elasticsearch-jdbc-2.3.4.0.jar:?]
        at org.xbib.tools.JDBCImporter.process(JDBCImporter.java:199) ~[elasticsearch-jdbc-2.3.4.0.jar:?]
        at org.xbib.tools.JDBCImporter.newRequest(JDBCImporter.java:185) [elasticsearch-jdbc-2.3.4.0.jar:?]
        at org.xbib.tools.JDBCImporter.newRequest(JDBCImporter.java:51) [elasticsearch-jdbc-2.3.4.0.jar:?]
        at org.xbib.pipeline.AbstractPipeline.call(AbstractPipeline.java:50) [elasticsearch-jdbc-2.3.4.0.jar:?]
        at org.xbib.pipeline.AbstractPipeline.call(AbstractPipeline.java:16) [elasticsearch-jdbc-2.3.4.0.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.io.IOException: 打开的文件过多( this mean "Open file too much")
        at sun.nio.ch.EPollArrayWrapper.epollCreate(Native Method) ~[?:1.8.0_101]
        at sun.nio.ch.EPollArrayWrapper.<init>(EPollArrayWrapper.java:130) ~[?:1.8.0_101]
        at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:69) ~[?:1.8.0_101]
        at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36) ~[?:1.8.0_101]
        at java.nio.channels.Selector.open(Selector.java:227) ~[?:1.8.0_101]
        at org.jboss.netty.channel.socket.nio.SelectorUtil.open(SelectorUtil.java:63) ~[netty-3.10.5.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.openSelector(AbstractNioSelector.java:360) ~[netty-3.10.5.Final.jar:?]
        ... 31 more
][ERROR][importer.jdbc            ][pool-606-thread-1] error while processing request: Failed to create a selector.
org.jboss.netty.channel.ChannelException: Failed to create a selector.

**Comment by jprante** [comment]
Do not use 

` "interval" : "1s"`

It will blow all resources over the limit.

You have already set `schedule`, so `interval` is not needed.

**Comment by xjpphp** [comment]
Thank you.I've already done it.
But I found that the data is updated every second, not every minute updates.
How to configure “schedule”？

**Comment by jprante** [comment]
You have it already configured: `"schedule" : "* 0/1 * * * ?"`

**Comment by xjpphp** [comment]
I find two new error like blow:
1.
[ERROR][importer.jdbc  ][pool-5358-thread-1] error while processing request: Guice creation errors:2 errors
org.elasticsearch.common.inject.CreationException: Guice creation errors:

2.
[ERROR][importer.jdbc            ][pool-2-thread-2] unable to create new native thread
java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method) ~[?:1.8.0_101]
        at java.lang.Thread.start(Thread.java:714) ~[?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950) ~[?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357) ~[?:1.8.0_101]
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) ~[?:1.8.0_101]
        at org.xbib.pipeline.SimplePipelineExecutor.execute(SimplePipelineExecutor.java:105) ~[elasticsearch-jdbc-2.3.4.0.jar:?]
        at org.xbib.pipeline.MetricSimplePipelineExecutor.execute(MetricSimplePipelineExecutor.java:52) ~[elasticsearch-jdbc-2.3.4.0.jar:?]
        at org.xbib.tools.JDBCImporter.execute(JDBCImporter.java:237) ~[elasticsearch-jdbc-2.3.4.0.jar:?]
        at org.xbib.tools.JDBCImporter.run(JDBCImporter.java:146) [elasticsearch-jdbc-2.3.4.0.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_101]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
