### ISSUE TITLE
which version supply jdk 1.7?

### ISSUE THREAD

**Issue by liguoli323** [jprante/elasticsearch-jdbc#913]
use elasticsearch-jdbc-2.3.4.0 and elasticsearch-2.3.4 has an error ,java version "1.7.0_25"
when I use the below script, then occour an error : 
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/xbib/tools/Runner : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:792)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

script:

#!/bin/sh
bin=$JDBC_IMPORTER_HOME/bin
lib=$JDBC_IMPORTER_HOME/lib
echo '{
"type" : "jdbc",
"jdbc": {
"elasticsearch.autodiscover":true,
"elasticsearch.cluster":"log_es_cluster", 
"url":"jdbc:mysql://xxx/xxx",
"user":"admin", 
"password":"xxx",
"sql":"select * from t",
"elasticsearch" : {
  "host" : "xxx",
  "port" : 9200
},
"index" : "test",
"type" : "test"
}
}'| java -cp "${lib}/*" -Dlog4j.configurationFile=${bin}/log4j2.xml org.xbib.tools.Runner org.xbib.tools.JDBCImporter

**Comment by liguoli323** [comment]
anybody can tell me?

**Comment by hongjunsu** [comment]
it so clear , jdk must use 1.8
