### ISSUE TITLE
ojdbc14.jar it didn't work. can't find jdbc oracle connector.

### ISSUE THREAD

**Issue by sangyun765** [jprante/elasticsearch-jdbc#916]
version list
oracle db : my oracle db version is 10g released 2 (10.2.0.5)
ES : 2.3.4
jdbc importer : 2.3.4.1 

Hello!! I'm user who thanks for your work. 

I already checked other simliar issue that is https://github.com/jprante/elasticsearch-jdbc/issues/764.
I did your option. check my oracle jdbc connector if it isn't in 'lib'. 

I did. I have ojdbc14.jar in this file path (C:\Users\datasolution\Desktop\elk\elasticsearch-jdbc-2.3.4.1\lib). but JDBC IMPORTER didn't work.
I saw your source on github. I can't find 'oracle' work in your code. never. my ES version is 2.3.4. so your code version is 2.3.4.1 that I checked. I need another solution. plz, say something to me.  

This is error code.
[18:05:55,071][ERROR][importer.jdbc.source.standard][pool-2-thread-1] while opening read connection: jdbc:oracle:thin:@//192.168.1.1:1521/k3 No suitle driver found for jdbc:oracle:thin:@//192.168.1.1:1521/k3
java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@//192.168.1.1:1521/k3
        at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_111]
        at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_111]
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSource.getConnectionForReading(StandardSource.java:485) [elasticsearch-jdbc-2.3.4.1
ar:?]
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSource.execute(StandardSource.java:670) [elasticsearch-jdbc-2.3.4.1.jar:?]
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSource.fetch(StandardSource.java:597) [elasticsearch-jdbc-2.3.4.1.jar:?]
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardContext.fetch(StandardContext.java:191) [elasticsearch-jdbc-2.3.4.1.jar:?]
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardContext.execute(StandardContext.java:166) [elasticsearch-jdbc-2.3.4.1.jar:?]
        at org.xbib.tools.JDBCImporter.process(JDBCImporter.java:203) [elasticsearch-jdbc-2.3.4.1.jar:?]
        at org.xbib.tools.JDBCImporter.newRequest(JDBCImporter.java:189) [elasticsearch-jdbc-2.3.4.1.jar:?]
        at org.xbib.tools.JDBCImporter.newRequest(JDBCImporter.java:53) [elasticsearch-jdbc-2.3.4.1.jar:?]
        at org.xbib.pipeline.AbstractPipeline.call(AbstractPipeline.java:50) [elasticsearch-jdbc-2.3.4.1.jar:?]
        at org.xbib.pipeline.AbstractPipeline.call(AbstractPipeline.java:16) [elasticsearch-jdbc-2.3.4.1.jar:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_111]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
java.io.IOException: pool did not terminate
        at org.xbib.tools.JDBCImporter.shutdown(JDBCImporter.java:265)
        at org.xbib.tools.JDBCImporter$2.run(JDBCImporter.java:322)

**Comment by jprante** [comment]
I do not include Oracle-specific code. This is a JDBC-based tool for all JDBC drivers.

Oracle 10.2.0.5 is unsupported according to Oracle:

http://www.oracle.com/technetwork/database/features/jdbc/index-091264.html

`ojdbc14.jar` is for Java 1.5 and does not work with JDBC importer.

Use always latest JDBC driver version possible certified by Oracle for JDK 7 and JDK 8 (ojdbc7.jar)

http://www.oracle.com/technetwork/database/features/jdbc/default-2280470.html

**Comment by sangyun765** [comment]
thanks a lot. ojdbc7.jar is working.
