### ISSUE TITLE
There are aways errors after runing a few days.

### ISSUE THREAD

**Issue by woshibushibu** [jprante/elasticsearch-jdbc#945]
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method) ~[?:1.8.0_91]
	at java.lang.Thread.start(Thread.java:714) ~[?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950) ~[?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357) ~[?:1.8.0_91]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) ~[?:1.8.0_91]
	at org.xbib.pipeline.SimplePipelineExecutor.execute(SimplePipelineExecutor.java:105) ~[elasticsearch-jdbc-2.3.3.0.jar:?]
	at org.xbib.pipeline.MetricSimplePipelineExecutor.execute(MetricSimplePipelineExecutor.java:52) ~[elasticsearch-jdbc-2.3.3.0.jar:?]
	at org.xbib.tools.JDBCImporter.execute(JDBCImporter.java:237) ~[elasticsearch-jdbc-2.3.3.0.jar:?]
	at org.xbib.tools.JDBCImporter.run(JDBCImporter.java:146) [elasticsearch-jdbc-2.3.3.0.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_91]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

**Comment by woshibushibu** [comment]
The memory has never been used more than 60%.

**Comment by woshibushibu** [comment]
By the way, and after that, I  cannot connect to the server with ssh even through local shell
