### ISSUE TITLE
ERROR [importer.jdbc]OOM:unable to create new native thread

### ISSUE THREAD

**Issue by scalaLearn** [jprante/elasticsearch-jdbc#960]
I run a scheduler with 'schedule=0/10 0-59 0-23 ? * *'.
But,after 20 hours,OOM error happened ....

Here is my script:

#!/bin/sh
bin=/home/ch_wltas/es/elasticsearch-2.3.4/elasticsearch-jdbc-2.3.4.0/bin
lib=/home/ch_wltas/es/elasticsearch-2.3.4/elasticsearch-jdbc-2.3.4.0/lib
echo '{
"type" : "jdbc",
"jdbc": {
"url":"jdbc:mysql://xx.xx.xx.xx:xxxx/chmpldb" , 
"user":"user",
"password":"password",
"statefile":"es_shop_update.json",
"schedule" : "0/10 0-59 0-23 ? * *",
"metrics" : {
    "enabled" : true,
    "logger" : {
        "plain" : false,
        "json" : true
                }
        },
"sql" :  [{
        "statement" : "shop_update.sql",
                "parameter" : ["$metrics.lastexecutionstart"]
    }],
"elasticsearch" : {
    "host" : "xx.xx.xxx.xxx",
    "port" : 9300,
    "cluster":"clusterName",
    "autodiscover":true
    },
    "index" : "testshop", 
    "type" : "shop" ,
        "index_settings" : {
             "index" : {
                 "number_of_shards" : 5
             }
         },
       "type_mapping": {
             "shop" : {
                 "_all":{
                     "analyzer":"ik_smart",
                     "search_analyzer":"ik_smart",
                     "term_vector":"no",
                     "store":"false"
                 },
                 "properties" : {
                     "location" : {
                         "type" : "geo_point"
                     }
                 }
             }
         }
    }
   }'| java \
      -cp "${lib}/*" \
        -Dlog4j.configurationFile=${bin}/log4j2.xml \
          org.xbib.tools.Runner \
            org.xbib.tools.JDBCImporter

after 20 hours,there are errors like：
[importer.jdbc            ][pool-4787-thread-1] error while processing request: no cluster nodes available, check settings {autodiscover=true, client.transport.ignore_cluster_name=false, client.transport.nodes_sampler_interval=5s, client.transport.ping_timeout=5s, cluster.name=clusterName, flush_interval=5s, host.0=xx.xx.xxx.xxx, max_actions_per_request=10000, max_concurrent_requests=4, max_volume_per_request=10mb, name=importer, port=9300, sniff=false}
org.elasticsearch.client.transport.NoNodeAvailableException: no cluster nodes available, check settings {autodiscover=true, client.transport.ignore_cluster_name=false, client.transport.nodes_sampler_interval=5s, client.transport.ping_timeout=5s, cluster.name=clusterName, flush_interval=5s, host.0=172.17.254.166, max_actions_per_request=10000, max_concurrent_requests=4, max_volume_per_request=10mb, name=importer, port=9300, sniff=false}
        at org.xbib.elasticsearch.helper.client.BulkTransportClient.init(BulkTransportClient.java:164) ~[elasticsearch-helper-2.3.4.0.jar:?]
        at org.xbib.elasticsearch.helper.client.ClientBuilder.toBulkTransportClient(ClientBuilder.java:113) ~[elasticsearch-helper-2.3.4.0.jar:?]
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSink.createClient(StandardSink.java:348) ~[elasticsearch-jdbc-2.3.4.0.jar:?]
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardSink.beforeFetch(StandardSink.java:100) ~[elasticsearch-jdbc-2.3.4.0.jar:?]
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardContext.beforeFetch(StandardContext.java:183) ~[elasticsearch-jdbc-2.3.4.0.jar:?]
        at org.xbib.elasticsearch.jdbc.strategy.standard.StandardContext.execute(StandardContext.java:164) ~[elasticsearch-jdbc-2.3.4.0.jar:?]
        at org.xbib.tools.JDBCImporter.process(JDBCImporter.java:199) ~[elasticsearch-jdbc-2.3.4.0.jar:?]
        at org.xbib.tools.JDBCImporter.newRequest(JDBCImporter.java:185) [elasticsearch-jdbc-2.3.4.0.jar:?]
        at org.xbib.tools.JDBCImporter.newRequest(JDBCImporter.java:51) [elasticsearch-jdbc-2.3.4.0.jar:?]
        at org.xbib.pipeline.AbstractPipeline.call(AbstractPipeline.java:50) [elasticsearch-jdbc-2.3.4.0.jar:?]
        at org.xbib.pipeline.AbstractPipeline.call(AbstractPipeline.java:16) [elasticsearch-jdbc-2.3.4.0.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[08:32:45,024][WARN ][org.elasticsearch.threadpool][elasticsearch[importer][scheduler][T#1]] [importer] failed to run [threaded] org.elasticsearch.client.transport.TransportClientNodesService$ScheduledNodeSampler@5208fc00
java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method) ~[?:1.8.0_121]
        at java.lang.Thread.start(Thread.java:714) ~[?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950) ~[?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1368) ~[?:1.8.0_121]
        at org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor.execute(EsThreadPoolExecutor.java:85) ~[elasticsearch-2.3.4.jar:2.3.4]
        at org.elasticsearch.threadpool.ThreadPool$ThreadedRunnable.run(ThreadPool.java:676) ~[elasticsearch-2.3.4.jar:2.3.4]
        at org.elasticsearch.threadpool.ThreadPool$LoggingRunnable.run(ThreadPool.java:640) [elasticsearch-2.3.4.jar:2.3.4]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_121]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

Here is elasticsearch configuration:
elasticsearch:
export ES_HEAP_SIZE=1g
elasticsearch.yml:
cluster.name: clusterName
bootstrap.mlockall:true

**Comment by scalaLearn** [comment]
@jprante
